/**
 * Settings page
 */

import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/features/auth';
import { getStorage } from '@/lib/storage';
import { useXmtpStore } from '@/lib/stores/xmtp-store';
import { getXmtpClient } from '@/lib/xmtp';
import { InstallationsSettings } from './InstallationsSettings';
import { useWalletConnection, wagmiConfigNative } from '@/lib/wagmi';
import { getPublicClient } from '@wagmi/core';
import { IdentifierKind } from '@xmtp/browser-sdk';
import { QRCodeOverlay } from '@/components/QRCodeOverlay';
import {
  disablePush,
  enablePushForCurrentUser,
  getAppPushStatus,
  getPushPermissionStatus,
  preparePushBrowserResources,
  type AppPushStatus,
} from '@/lib/push';
import { exportIdentityToKeyfile, serializeKeyfile } from '@/lib/keyfile';
import { FarcasterSettings } from './FarcasterSettings';
import { getInboxConnectionWalletOptions } from '@/lib/wagmi/inbox-connection-options';
import { isAutoGeneratedDisplayName, suggestAnimalDisplayName } from '@/lib/identity/profile-suggestions';
import { formatWalletConnectionError } from '@/features/auth/wallet-connection-error';
import {
  ethereumAddressesEqual,
  normalizeEthereumAddress,
  requireEthereumAddress,
} from '@/lib/utils/ethereum';
import { classifyWalletBytecode } from '@/lib/wagmi/wallet-account';
import {
  extractInstallationLimitInboxId,
  shortInboxId,
} from '@/lib/xmtp/installation-recovery';
import buildInfo from '@/build-info.json';
import {
  isWalletInspectionRequiredError,
  requireWalletTypeHintChain,
  WalletInspectionRequiredError,
  walletInspectionChainIds,
  withWalletInspectionTimeout,
  type WalletTypeHint,
} from '@/lib/wagmi/wallet-inspection';

type WalletSignMessage = (message: string, accountAddress?: string) => Promise<string>;
interface InstallationRecoveryResult {
  revoked: string[];
  inboxId?: string;
  installationCount?: number;
}
interface InstallationRecoveryOptions {
  inboxId?: string;
  chainId?: number;
  walletType?: WalletTypeHint;
  onStatus?: (message: string) => void;
}
interface ConnectedWalletSnapshot {
  address: string;
  chainId?: number;
  signMessage: (message: string) => Promise<string>;
}

function isInstallationLimitError(message: string | null | undefined): boolean {
  if (!message) return false;
  return /10\/10|installation limit|already registered 10/i.test(message);
}

function isStaleSetupInstallationError(message: string | null | undefined): boolean {
  return Boolean(message && /interrupted browser installation|interrupted setup installation/i.test(message));
}

function isLegacyScwChainZeroRecoveryError(message: string | null | undefined): boolean {
  return Boolean(message && /SCW chain ID 0|WalletConnect alone/i.test(message));
}

export function SettingsPage() {
  const navigate = useNavigate();
  const {
    identity,
    logout,
    burnIdentity,
    reconnectCurrentIdentity,
    addDeviceToExistingWalletInbox,
  } = useAuth();
  const { connectionStatus, lastConnected, error: xmtpError } = useXmtpStore();
  const [storageSize, setStorageSize] = useState<number | null>(null);
  const [isLoadingSize, setIsLoadingSize] = useState(false);
  const [isEditingName, setIsEditingName] = useState(false);
  const computeInitialDisplayName = () => {
    const raw = identity?.displayName?.trim();
    if (!raw || isAutoGeneratedDisplayName(raw)) {
      const seed = identity?.inboxId || identity?.address;
      return suggestAnimalDisplayName(seed).displayName;
    }
    return raw;
  };

  const [displayName, setDisplayName] = useState<string>(computeInitialDisplayName());
  const avatarInputRef = useRef<HTMLInputElement>(null);
  const {
    disconnectWallet,
    connectWallet,
    walletOptions,
    isConnected: isWalletConnected,
    address: walletAddress,
    chainId: connectedWalletChainId,
    signMessage,
  } = useWalletConnection();
  const [showQR, setShowQR] = useState(false);
  // Track push status
  const [pushStatus, setPushStatus] = useState<'unknown' | AppPushStatus['state']>('unknown');
  const [pushDetails, setPushDetails] = useState<AppPushStatus | null>(null);
  const [isPushLoading, setIsPushLoading] = useState(false);
  const [pushPreparation, setPushPreparation] = useState<'preparing' | 'ready' | 'retry'>('preparing');
  const [pushFeedback, setPushFeedback] = useState<{
    tone: 'info' | 'success' | 'error';
    message: string;
  } | null>(null);
  const [isReconnecting, setIsReconnecting] = useState(false);
  const [connectError, setConnectError] = useState<string | null>(null);
  const [showConnectorList, setShowConnectorList] = useState(false);
  const [showAddIdentityModal, setShowAddIdentityModal] = useState(false);
  const [isAddingIdentity, setIsAddingIdentity] = useState(false);
  const [addIdentityError, setAddIdentityError] = useState<string | null>(null);
  const [isBurningInbox, setIsBurningInbox] = useState(false);
  const canDownloadKeyfile = Boolean(identity?.privateKey || identity?.mnemonic);

  useEffect(() => {
    try {
      const params = new URLSearchParams(window.location.search);
      if (params.get('connectInbox') === '1') {
        setAddIdentityError(null);
        setShowAddIdentityModal(true);
        navigate('/settings', { replace: true });
      }
    } catch {
      // ignore malformed URLs
    }
  }, [navigate]);

  // Helper to reconnect to XMTP
  const handleReconnect = async (connectedWallet?: ConnectedWalletSnapshot) => {
    if (!identity || isReconnecting) return;

    setIsReconnecting(true);
    try {
      setConnectError(null);
      setShowConnectorList(false);
      // If identity has a private key (Converge-generated), use it directly
      if (identity.privateKey) {
        await reconnectCurrentIdentity();
        return;
      }

      // For wallet-connected identities, ensure the wallet is connected to the right address
      const walletSnapshot = connectedWallet;
      const effectiveWallet = walletSnapshot?.address ?? walletAddress;
      try {
        if (
          !walletSnapshot &&
          (!isWalletConnected || !ethereumAddressesEqual(effectiveWallet, identity.address))
        ) {
          setShowConnectorList(true);
          setConnectError(
            effectiveWallet && !ethereumAddressesEqual(effectiveWallet, identity.address)
              ? 'Please connect the wallet that owns this identity to continue.'
              : 'Choose a wallet to reconnect.'
          );
          return;
        }
      } catch (connectErr) {
        console.error('Wallet connection failed:', connectErr);
        setConnectError(formatWalletConnectionError(connectErr));
        setShowConnectorList(true);
        return;
      }

      if (!ethereumAddressesEqual(effectiveWallet, identity.address)) {
        throw new Error('Please connect the wallet that owns this identity to continue.');
      }

      const effectiveSignMessage = walletSnapshot?.signMessage ?? signMessage;
      if (!effectiveSignMessage) {
        throw new Error('Wallet signing is not available. Try reconnecting your wallet.');
      }

      await reconnectCurrentIdentity({
        chainId: walletSnapshot?.chainId ?? connectedWalletChainId,
        walletType: identity.walletType,
        signMessage: async (message: string) =>
          walletSnapshot
            ? await effectiveSignMessage(message)
            : await effectiveSignMessage(message, identity.address),
      });
    } catch (error) {
      console.error('Reconnect failed:', error);
      if (!showConnectorList && !isWalletConnected) {
        setShowConnectorList(true);
      }
      setConnectError(error instanceof Error ? error.message : 'Failed to reconnect wallet');
    } finally {
      setIsReconnecting(false);
    }
  };

  // Check push status on mount
  useEffect(() => {
    const checkPushStatus = async () => {
      const permission = getPushPermissionStatus();
      if (permission === 'unsupported') {
        setPushStatus('unsupported');
        return;
      }
      const status = await getAppPushStatus();
      setPushDetails(status);
      setPushStatus(status.state);
    };
    checkPushStatus();
    if (getPushPermissionStatus() !== 'unsupported') {
      void preparePushBrowserResources()
        .then(() => setPushPreparation('ready'))
        .catch(() => setPushPreparation('retry'));
    }
  }, []);

  const handleEnablePush = async () => {
    if (isPushLoading) return;
    setIsPushLoading(true);
    setPushFeedback(null);
    try {
      if (pushPreparation !== 'ready') {
        setPushPreparation('preparing');
        try {
          await preparePushBrowserResources();
          setPushPreparation('ready');
          setPushFeedback({
            tone: 'info',
            message: 'Notification support is ready. Turn the switch on again to approve notifications.',
          });
        } catch (error) {
          setPushPreparation('retry');
          setPushFeedback({
            tone: 'error',
            message: `Unable to prepare notifications: ${error instanceof Error ? error.message : 'Unknown error'}`,
          });
        }
        return;
      }
      const result = await enablePushForCurrentUser();

      if (result.success) {
        const status = await getAppPushStatus();
        setPushDetails(status);
        setPushStatus(status.state);
        setPushFeedback({
          tone: 'success',
          message: `Experimental notifications registered for ${status.registeredInboxCount} of ${status.expectedInboxCount} loaded inboxes. Continuous automatic delivery still needs the always-on XMTP listener.`,
        });
      } else {
        const status = await getAppPushStatus();
        setPushDetails(status);
        setPushStatus(status.state);
        setPushFeedback({
          tone: 'error',
          message: result.error || 'Failed to enable notifications.',
        });
      }
    } catch (e) {
      console.warn('[Settings] Enable push failed', e);
      setPushFeedback({
        tone: 'error',
        message: e instanceof Error ? e.message : 'Failed to enable notifications.',
      });
    } finally {
      setIsPushLoading(false);
    }
  };

  const handleDisablePush = async () => {
    if (isPushLoading) return;
    setIsPushLoading(true);
    setPushFeedback(null);
    try {
      const success = await disablePush();
      const status = await getAppPushStatus();
      setPushDetails(status);
      setPushStatus(status.state);
      if (success && status.pendingDeletionCount === 0) {
        setPushFeedback({ tone: 'success', message: 'Notifications disabled.' });
      } else if (status.pendingDeletionCount > 0) {
        setPushFeedback({
          tone: 'error',
          message: `Browser notifications are off, but ${status.pendingDeletionCount} relay registration${status.pendingDeletionCount === 1 ? '' : 's'} could not be deleted. Retry this toggle when online.`,
        });
      } else {
        setPushFeedback({ tone: 'error', message: 'Failed to disable notifications.' });
      }
    } catch (e) {
      console.warn('[Settings] Disable push failed', e);
      setPushFeedback({
        tone: 'error',
        message: e instanceof Error ? e.message : 'Failed to disable notifications.',
      });
    } finally {
      setIsPushLoading(false);
    }
  };

  const handleBurnInbox = async () => {
    if (!identity?.inboxId || isBurningInbox) return;
    const label = identity.displayName?.trim() || 'this inbox';
    if (!confirm(`Burn ${label}? This removes its key, messages, contacts, profile, attachments, and local XMTP database from this browser.`)) {
      return;
    }

    setIsBurningInbox(true);
    try {
      const result = await burnIdentity(identity.inboxId);
      if (!result.localDataRemoved) {
        alert(
          `Burn Inbox could not finish the local wipe. The inbox key and switcher entry were kept so you can retry. Close other Converge tabs, then try again.\n\n${result.localCleanupWarnings.join('\n')}`
        );
        setIsBurningInbox(false);
        return;
      }
      try {
        await disconnectWallet();
      } catch (error) {
        console.warn('[Settings] Wallet disconnect after Burn Inbox failed (non-fatal):', error);
      }

      const warnings = [
        result.pushWarning,
        result.revokeWarning,
        ...result.localCleanupWarnings,
      ].filter((message): message is string => Boolean(message));
      if (warnings.length > 0) {
        alert(`Inbox data removal completed with warnings:\n\n${warnings.join('\n')}`);
      }

      window.location.assign(result.intentionallyEmpty ? '/onboarding' : '/');
    } catch (error) {
      console.error('Failed to burn inbox:', error);
      alert(error instanceof Error ? error.message : 'Failed to burn inbox');
      setIsBurningInbox(false);
    }
  };

  const handleAvatarChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Check file size (max 256KB to keep XMTP messages small)
    if (file.size > 256 * 1024) {
      alert('Avatar image must be less than 256KB');
      return;
    }

    // Check file type
    if (!file.type.startsWith('image/')) {
      alert('Please select an image file');
      return;
    }

    try {
      // Convert to data URI
      const reader = new FileReader();
      reader.onload = async (event) => {
        const dataUri = event.target?.result as string;

        // Update identity with avatar
        if (identity) {
          const storage = await getStorage();
          const updatedIdentity = { ...identity, avatar: dataUri };
          await storage.putIdentity(updatedIdentity);

          // Persist to XMTP so it survives clear-all
          try {
            const xmtp = getXmtpClient();
            await xmtp.saveProfile(updatedIdentity.displayName, dataUri);
          } catch (err) {
            console.warn('[Settings] Failed to save avatar to network (non-fatal):', err);
          }

          window.location.reload(); // Refresh to show new avatar
        }
      };
      reader.readAsDataURL(file);
    } catch (error) {
      console.error('Failed to update avatar:', error);
      alert('Failed to update avatar');
    }
  };

  const handleSaveDisplayName = async () => {
    try {
      if (identity) {
        const storage = await getStorage();
        const updatedIdentity = { ...identity, displayName: displayName.trim() };
        await storage.putIdentity(updatedIdentity);
        // Persist to XMTP so it survives clear-all
        try {
          const xmtp = getXmtpClient();
          await xmtp.saveProfile(updatedIdentity.displayName, updatedIdentity.avatar);
        } catch (err) {
          console.warn('[Settings] Failed to save display name to network (non-fatal):', err);
        }
        setIsEditingName(false);
        window.location.reload(); // Refresh to show new name
      }
    } catch (error) {
      console.error('Failed to update display name:', error);
      alert('Failed to update display name');
    }
  };

  // Keep suggested name in sync when identity changes
  useEffect(() => {
    setDisplayName(computeInitialDisplayName());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [identity?.inboxId, identity?.address, identity?.displayName]);

  const resolveWalletInboxTarget = async (
    accounts: string[],
    connectedChainId?: number,
    walletTypeHint?: WalletTypeHint
  ): Promise<{ address: string; walletType?: 'EOA' | 'SCW'; chainId?: number } | null> => {
    const normalized = Array.from(
      new Set(
        accounts
          .map((account) => normalizeEthereumAddress(account))
          .filter((account): account is `0x${string}` => Boolean(account))
      )
    );
    if (normalized.length === 0) return null;

    // Prefer a non-app-key address if multiple accounts are returned.
    const notMine = identity?.address
      ? normalized.find((account) => !ethereumAddressesEqual(account, identity.address))
      : undefined;
    const address = notMine ?? normalized[0];

    if (walletTypeHint) {
      return {
        address,
        walletType: walletTypeHint,
        chainId: requireWalletTypeHintChain(walletTypeHint, connectedChainId),
      };
    }

    // Inspect the connector's chain first, then Base as the common smart-wallet
    // fallback. The selected chain must be carried into the SCW signer.
    const inspections = await Promise.all(
      walletInspectionChainIds(connectedChainId).flatMap((inspectionChainId) => {
        const publicClient = getPublicClient(wagmiConfigNative, {
          chainId: inspectionChainId,
        });
        if (!publicClient) return [];
        return normalized.map(async (account) => {
        try {
          const bytecode = await withWalletInspectionTimeout(
            publicClient.getBytecode({ address: account })
          );
            return { account, inspectionChainId, bytecode };
        } catch (error) {
          console.warn(
            `[Settings] Could not inspect wallet bytecode on chain ${inspectionChainId}:`,
            error
          );
            return null;
        }
        });
      })
    );
    const successfulInspections = inspections.filter(
      (inspection): inspection is NonNullable<typeof inspection> => Boolean(inspection)
    );
    const smartAccountInspection = successfulInspections.find(
      ({ bytecode }) => classifyWalletBytecode(bytecode) === 'SCW'
    );
    if (smartAccountInspection) {
      return {
        address: smartAccountInspection.account,
        walletType: 'SCW',
        chainId: smartAccountInspection.inspectionChainId,
      };
    }
    if (successfulInspections.length === 0) {
      throw new WalletInspectionRequiredError();
    }

    return { address, walletType: 'EOA' };
  };

  const connectExistingWalletInbox = async (
    accounts: readonly string[] | undefined,
    walletSignMessage = signMessage,
    onStatus?: (message: string) => void,
    connectedChainId?: number,
    walletTypeHint?: WalletTypeHint
  ) => {
    const addressList = Array.from(new Set((accounts ?? []).filter(Boolean)));
    const target = await resolveWalletInboxTarget(
      addressList,
      connectedChainId,
      walletTypeHint
    );

    if (!target) {
      throw new Error('No wallet address was returned. Try connecting your wallet again.');
    }
    if (!walletSignMessage) {
      throw new Error('Wallet signing is not available. Connect your wallet and try again.');
    }

    const result = await addDeviceToExistingWalletInbox(
      target.address,
      target.chainId,
      async (message: string) => await walletSignMessage(message, target.address),
      {
        walletType: target.walletType,
        label: `Wallet ${target.address.slice(0, 6)}…${target.address.slice(-4)}`,
        onStatus,
      }
    );

    console.info('[Settings] Added a fresh local account key to existing inbox', {
      targetAddress: target.address,
      targetWalletType: target.walletType,
      targetChainId: target.chainId ?? null,
      deviceKeyAddress: result.deviceKeyAddress,
      inboxId: result.inboxId,
      installationId: result.installationId,
    });

    alert(
      `Added this browser to inbox ${result.inboxId} with a new local account key.\n\nYour previous Converge inbox and key were not moved or abandoned. Keep an older device online while history sync runs.`
    );
    window.location.assign('/');
  };
  const revokeOldInstallationsForExistingWalletInbox = async (
    accounts: readonly string[] | undefined,
    walletSignMessage = signMessage,
    options: InstallationRecoveryOptions = {}
  ): Promise<InstallationRecoveryResult> => {
    const addressList = Array.from(new Set((accounts ?? []).filter(Boolean)));
    const target = await resolveWalletInboxTarget(
      addressList,
      options.chainId,
      options.walletType
    );

    if (!target) {
      throw new Error('No wallet address was returned. Try connecting your wallet again.');
    }
    if (!walletSignMessage) {
      throw new Error('Wallet signing is not available. Connect your wallet and try again.');
    }

    console.info('[Settings] Starting existing inbox installation recovery', {
      targetAddress: target.address,
      walletType: target.walletType,
      chainId: target.chainId,
      inboxId: options.inboxId,
    });
    options.onStatus?.(`Preparing recovery for wallet ${target.address.slice(0, 6)}...${target.address.slice(-4)}.`);

    const xmtp = getXmtpClient();
    const probe = await xmtp.probeIdentity({
      address: target.address,
      chainId: target.chainId,
      walletType: target.walletType,
      signMessage: async (message: string) => await walletSignMessage(message, target.address),
    });
    const recoveryIdentifier = probe.inboxState?.recoveryIdentifier;
    const recoveryAddress =
      recoveryIdentifier?.identifierKind === IdentifierKind.Ethereum
        ? normalizeEthereumAddress(recoveryIdentifier.identifier)
        : null;
    if (!recoveryAddress || recoveryAddress !== requireEthereumAddress(target.address)) {
      throw new Error(
        `Static recovery requires the inbox recovery wallet${recoveryAddress ? ` (${recoveryAddress})` : ''}. Connect that wallet or revoke an installation from an existing device.`
      );
    }
    if (options.inboxId && probe.inboxId?.toLowerCase() !== options.inboxId.toLowerCase()) {
      throw new Error('The connected recovery wallet no longer resolves to the blocked inbox.');
    }
    const storage = await getStorage();
    const pendingIdentity = (await storage.listIdentities()).find(
      (candidate) =>
        candidate.provisioningMode === 'device-join' &&
        candidate.provisioningPending === true &&
        candidate.expectedInboxId?.trim().toLowerCase() === probe.inboxId?.trim().toLowerCase()
    );
    const staleInstallationId = pendingIdentity?.staleInstallationId;
    const staleInstallationIsRegistered = Boolean(
      staleInstallationId &&
        probe.inboxState?.installations?.some(
          (installation) =>
            installation.id.replace(/^0x/i, '').toLowerCase() ===
            staleInstallationId.replace(/^0x/i, '').toLowerCase()
        )
    );
    if (staleInstallationId && !staleInstallationIsRegistered) {
      await storage.putIdentity({ ...pendingIdentity, staleInstallationId: undefined });
      throw new Error(
        'The interrupted installation is no longer registered. Retry Approve This Device.'
      );
    }
    const result = await xmtp.revokeOldestInstallationsForIdentity(
      {
        address: target.address,
        chainId: target.chainId,
        walletType: target.walletType,
        signMessage: async (message: string) => await walletSignMessage(message, target.address),
      },
      Math.max(1, probe.installationCount - 9),
      {
        inboxId: options.inboxId,
        requireAtLimit: !staleInstallationIsRegistered,
        preferredInstallationId: staleInstallationIsRegistered
          ? staleInstallationId
          : undefined,
        onStatus: options.onStatus,
      }
    );
    if (
      pendingIdentity?.staleInstallationId &&
      result.revoked.some(
        (installationId) =>
          installationId.replace(/^0x/i, '').toLowerCase() ===
          pendingIdentity.staleInstallationId?.replace(/^0x/i, '').toLowerCase()
      )
    ) {
      let removalVisible = false;
      for (let attempt = 0; attempt < 10; attempt += 1) {
        const refreshed = await xmtp.probeIdentity({
          address: target.address,
          chainId: target.chainId,
          walletType: target.walletType,
          signMessage: async (message: string) => await walletSignMessage(message, target.address),
        });
        const stillRegistered = refreshed.inboxState?.installations?.some(
          (installation) =>
            installation.id.replace(/^0x/i, '').toLowerCase() ===
            pendingIdentity.staleInstallationId?.replace(/^0x/i, '').toLowerCase()
        );
        if (!stillRegistered) {
          removalVisible = true;
          break;
        }
        await new Promise((resolve) => setTimeout(resolve, 500));
      }
      if (!removalVisible) {
        throw new Error(
          'XMTP accepted the removal, but the interrupted installation is still visible. Wait a moment and retry recovery.'
        );
      }
      await storage.putIdentity({ ...pendingIdentity, staleInstallationId: undefined });
    }
    return result;
  };

  const handleAddIdentity = () => {
    setAddIdentityError(null);
    setShowAddIdentityModal(true);
  };

  const handleDownloadKeyfile = () => {
    try {
      if (!identity) {
        alert('No identity is currently loaded.');
        return;
      }

      if (!identity.privateKey && !identity.mnemonic) {
        alert('This identity is managed by an external wallet. Connect on the device where it was generated to export a keyfile.');
        return;
      }
      if (
        !window.confirm(
          'This keyfile contains an unencrypted private key or recovery phrase. Anyone with the file can use this XMTP identity. Continue?'
        )
      ) {
        return;
      }

      const keyfile = exportIdentityToKeyfile(identity);
      const serialized = serializeKeyfile(keyfile);
      const blob = new Blob([serialized], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const safeAddress = identity.address.replace(/[^a-zA-Z0-9]/g, '').slice(0, 10) || 'identity';
      const timestamp = new Date().toISOString().replace(/[:]/g, '-');
      const filename = `converge-keyfile-${safeAddress}-${timestamp}.json`;

      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = filename;
      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to export keyfile:', error);
      alert('Failed to export keyfile. Please try again.');
    }
  };

  const handleClearCache = async () => {
    try {
      // Clear all service worker caches
      if ('caches' in window) {
        const cacheNames = await caches.keys();
        await Promise.all(cacheNames.map(name => caches.delete(name)));
      }

      // Refresh service-worker scripts without unregistering their push state.
      if ('serviceWorker' in navigator) {
        const registrations = await navigator.serviceWorker.getRegistrations();
        await Promise.allSettled(registrations.map((reg) => reg.update()));
      }
      window.location.reload();
    } catch (error) {
      console.error('Failed to clear cache:', error);
      alert('Failed to clear cache');
    }
  };

  const handleClearData = async () => {
    if (
      confirm(
        'This will delete ALL your local data including messages, conversations, and XMTP databases. This action cannot be undone. Continue?'
      )
    ) {
      try {
        // Helper: robustly clear cookies for all paths/domains on this origin
        const clearAllCookies = async () => {
          try {
            const raw = document.cookie;
            if (!raw) return;
            const cookiePairs = raw.split(';');
            const names = cookiePairs
              .map((c) => c.trim())
              .filter(Boolean)
              .map((c) => (c.includes('=') ? c.slice(0, c.indexOf('=')) : c));

            // Generate domain variants: exact host, parent domains, and dotted forms
            const host = location.hostname;
            const parts = host.split('.');
            const domainVariants = new Set<string>([host]);
            for (let i = 0; i < parts.length; i++) {
              const dom = parts.slice(i).join('.');
              if (dom) {
                domainVariants.add(dom);
                domainVariants.add('.' + dom);
              }
            }

            // Generate path variants from deepest to root
            const path = location.pathname || '/';
            const segments = path.split('/').filter(Boolean);
            const pathVariants = new Set<string>(['/']);
            for (let i = 0; i < segments.length; i++) {
              pathVariants.add('/' + segments.slice(0, i + 1).join('/'));
            }

            const expires = 'Thu, 01 Jan 1970 00:00:00 GMT';
            const setExpired = (name: string, opts: string) => {
              try { document.cookie = `${name}=; Expires=${expires}; Max-Age=0; ${opts}`; } catch (e) { /* ignore set-cookie failure */ }
              try { document.cookie = `${name}=; Expires=${expires}; ${opts}`; } catch (e) { /* ignore set-cookie failure */ }
            };

            // Without domain attribute (current host implied)
            for (const name of names) {
              for (const p of pathVariants) {
                setExpired(name, `Path=${p}; SameSite=Lax`);
                // Try with Secure attribute as some cookies were set with SameSite=None; Secure
                setExpired(name, `Path=${p}; SameSite=None; Secure`);
              }
            }

            // With explicit domain attribute variants
            for (const name of names) {
              for (const d of domainVariants) {
                for (const p of pathVariants) {
                  setExpired(name, `Domain=${d}; Path=${p}; SameSite=Lax`);
                  setExpired(name, `Domain=${d}; Path=${p}; SameSite=None; Secure`);
                }
              }
            }
          } catch (err) {
            console.warn('[Settings] Failed to clear some cookies (non-fatal):', err);
          }
        };
        // Delete remote relay registrations while their local retry metadata is
        // still present. A failed relay cleanup blocks the destructive reset so
        // it can be retried instead of being stranded permanently.
        const pushCleanupComplete = await disablePush();
        const pushCleanupStatus = await getAppPushStatus();
        if (!pushCleanupComplete || pushCleanupStatus.pendingDeletionCount > 0) {
          alert(
            `Could not remove ${pushCleanupStatus.pendingDeletionCount || 'all'} push relay registration${pushCleanupStatus.pendingDeletionCount === 1 ? '' : 's'}. Check your connection and retry Clear All Browser Data.`
          );
          return;
        }

        // 1) Disconnect wallet to prevent auto-reconnect on next load
        try {
          await disconnectWallet();
          console.log('[Settings] Disconnected wallet via wagmi');
        } catch (e) {
          console.warn('[Settings] Wallet disconnect failed (non-fatal):', e);
        }

        // 2) Fully logout (disconnect XMTP, clear IndexedDB + XMTP OPFS, reset state)
        try {
          await logout();
          console.log('[Settings] Performed app logout and storage cleanup');
        } catch (e) {
          console.warn('[Settings] Logout encountered an error (continuing):', e);
        }

        // 3) Clear personalization reminder flags and any local/session storage app data
        try {
          if (typeof window !== 'undefined') {
            // Remove legacy global key
            try { window.localStorage.removeItem('personalization-reminder'); } catch (e) {
              console.warn('[Settings] Failed to remove legacy personalization key:', e);
            }
            // Remove per-identity keys
            try {
              const keys: string[] = [];
              for (let i = 0; i < window.localStorage.length; i++) {
                const k = window.localStorage.key(i);
                if (k) keys.push(k);
              }
              for (const k of keys) {
                if (k.startsWith('personalization-reminder:')) {
                  window.localStorage.removeItem(k);
                }
              }
            } catch (e) {
              console.warn('[Settings] Failed to enumerate personalization keys:', e);
            }
            // As this is "Clear All Data", clear all local/session storage as a final sweep
            try { window.localStorage.clear(); } catch (e) {
              console.warn('[Settings] Failed to clear localStorage:', e);
            }
            try { window.sessionStorage.clear(); } catch (e) {
              console.warn('[Settings] Failed to clear sessionStorage:', e);
            }
          }
        } catch (e) {
          console.warn('[Settings] Failed to clear personalization flags or web storage (non-fatal):', e);
        }

        // 4) Clear cookies for this origin (best-effort)
        await clearAllCookies();

        // 5) Clear service worker caches and unregister SW (force a fresh start)
        try {
          if ('caches' in window) {
            const cacheNames = await caches.keys();
            await Promise.all(cacheNames.map((name) => caches.delete(name)));
            console.log('[Settings] Cleared service worker caches');
          }
          if ('serviceWorker' in navigator) {
            // Unregister all known registrations
            const registrations = await navigator.serviceWorker.getRegistrations();
            await Promise.all(registrations.map((reg) => reg.unregister()));
            // Also try the current scope registration (Safari compatibility)
            try {
              const reg = await navigator.serviceWorker.getRegistration();
              if (reg) await reg.unregister();
            } catch (e) {
              console.warn('[Settings] SW getRegistration/unregister failed (non-fatal):', e);
            }
            console.log('[Settings] Unregistered service workers');
          }
        } catch (e) {
          console.warn('[Settings] Failed to clear SW caches or unregister SW (non-fatal):', e);
        }

        // 6) Trigger a hard reload with a clear flag to wipe databases on fresh load
        // This avoids "blocked" events from open connections in the current session
        console.log('[Settings] scheduling clear-all-data via reload');
        window.location.href = '/settings?clear_all_data=true';
      } catch (error) {
        console.error('Failed to clear data:', error);
        alert('Failed to clear data');
      }
    }
  };

  const loadStorageSize = async () => {
    setIsLoadingSize(true);
    try {
      const storage = await getStorage();
      const size = await storage.getStorageSize();
      setStorageSize(size);
    } catch (error) {
      console.error('Failed to load storage size:', error);
    } finally {
      setIsLoadingSize(false);
    }
  };

  const formatBytes = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  };

  const getConnectionStatusColor = () => {
    switch (connectionStatus) {
      case 'connected':
        return 'text-green-500';
      case 'connecting':
        return 'text-yellow-500';
      case 'error':
        return 'text-red-500';
      default:
        return 'text-primary-300';
    }
  };

  const getConnectionStatusText = () => {
    switch (connectionStatus) {
      case 'connected':
        return 'Connected';
      case 'connecting':
        return 'Connecting...';
      case 'error':
        return 'Connection Error';
      default:
        return 'Disconnected';
    }
  };

  const shouldShowReconnect = connectionStatus === 'error' || connectionStatus === 'disconnected';
  const walletNeedsReconnect = Boolean(identity && !identity.privateKey && !isWalletConnected);
  const pushIsOn = pushDetails?.enabledPreference ?? pushStatus === 'enabled';
  const pushDescription = (() => {
    if (pushStatus === 'unsupported') return 'Not supported in this browser';
    if (pushStatus === 'unknown') return 'Checking notification status...';
    if (!pushIsOn && pushPreparation === 'preparing') return 'Preparing notification support...';
    if (pushStatus === 'partial') {
      if (pushDetails?.pendingDeletionCount) {
        return `Notifications are off; ${pushDetails.pendingDeletionCount} relay cleanup ${pushDetails.pendingDeletionCount === 1 ? 'request is' : 'requests are'} pending`;
      }
      return `Experimental notifications active for ${pushDetails?.registeredInboxCount ?? 0} of ${pushDetails?.expectedInboxCount ?? 0} loaded inboxes`;
    }
    if (pushStatus === 'enabled') {
      return `Experimental notifications active for ${pushDetails?.registeredInboxCount ?? 0} loaded inbox${pushDetails?.registeredInboxCount === 1 ? '' : 'es'}`;
    }
    return 'Notify this browser about activity in loaded inboxes';
  })();

  return (
    <div className="flex flex-col h-full text-primary-50">
      {/* Header */}
      <div className="bg-primary-950/70 border-b border-primary-800/60 p-4 backdrop-blur-md">
        <div className="flex items-center justify-between max-w-2xl mx-auto">
          <h1 className="text-xl font-semibold">Settings</h1>
          <button onClick={() => navigate('/')} className="text-primary-200 hover:text-primary-100">
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto bg-primary-950/20">
        <div className="max-w-2xl mx-auto p-4 space-y-6">

          {/* Profile Section */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Profile</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg p-4 space-y-4 backdrop-blur">
              {/* Avatar */}
              <div className="flex items-center gap-4">
                <div className="relative">
                  <div className="w-20 h-20 rounded-full bg-primary-950/60 border border-primary-800/60 flex items-center justify-center overflow-hidden">
                    {identity?.avatar ? (
                      <img src={identity.avatar} alt="Avatar" className="w-full h-full object-cover" />
                    ) : (
                      <svg className="w-10 h-10 text-primary-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                        />
                      </svg>
                    )}
                  </div>
                  <button
                    onClick={() => avatarInputRef.current?.click()}
                    className="absolute bottom-0 right-0 bg-accent-500 hover:bg-accent-600 rounded-full p-1.5 transition-colors shadow-lg"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"
                      />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                  </button>
                  <input
                    ref={avatarInputRef}
                    type="file"
                    accept="image/*"
                    onChange={handleAvatarChange}
                    className="hidden"
                  />
                </div>
                <div className="flex-1">
                  <div className="text-sm text-primary-200 mb-1">Avatar</div>
                  <div className="text-sm text-primary-300">Click camera icon to change</div>
                </div>
              </div>

              {/* Display Name */}
              <div>
                <label className="block text-sm font-medium text-primary-200 mb-2">Display Name (Optional)</label>
                {isEditingName ? (
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={displayName}
                      onChange={(e) => setDisplayName(e.target.value)}
                      placeholder="Enter display name"
                      className="flex-1 bg-primary-950/60 border border-primary-800/60 rounded-lg px-3 py-2 text-sm text-primary-100 focus:outline-none focus:ring-2 focus:ring-accent-400 focus:ring-offset-2 focus:ring-offset-primary-950"
                      maxLength={50}
                    />
                    <button onClick={handleSaveDisplayName} className="btn-primary text-sm px-3">
                      Save
                    </button>
                    <button
                      onClick={() => {
                        // Reset to suggested/actual value on cancel
                        const raw = identity?.displayName?.trim();
                        if (!raw || isAutoGeneratedDisplayName(raw)) {
                          const seed = identity?.inboxId || identity?.address;
                          setDisplayName(suggestAnimalDisplayName(seed).displayName);
                        } else {
                          setDisplayName(raw);
                        }
                        setIsEditingName(false);
                      }}
                      className="btn-secondary text-sm px-3"
                    >
                      Cancel
                    </button>
                  </div>
                ) : (
                  <div className="flex items-center justify-between">
                    <span className="text-sm">
                      {identity?.displayName || <span className="text-primary-300">Not set</span>}
                    </span>
                    <button
                      onClick={() => {
                        // Prefill with suggested name when entering edit if auto-label
                        const raw = identity?.displayName?.trim();
                        if (!raw || isAutoGeneratedDisplayName(raw)) {
                          const seed = identity?.inboxId || identity?.address;
                          setDisplayName(suggestAnimalDisplayName(seed).displayName);
                        }
                        setIsEditingName(true);
                      }}
                      className="text-sm text-accent-300 hover:text-accent-200"
                    >
                      Edit
                    </button>
                  </div>
                )}
              </div>
            </div>
          </section>

          {/* Identity & Connection */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Identity & Connection</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              {/* XMTP Connection Status */}
              <div className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex-1">
                    <div className="font-medium">XMTP Network</div>
                    <div className="text-sm text-primary-200">Connection status</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-full ${getConnectionStatusColor()}`} />
                    <span className={`text-sm font-medium ${getConnectionStatusColor()}`}>
                      {getConnectionStatusText()}
                    </span>
                  </div>
                </div>
                {lastConnected && connectionStatus === 'connected' && (
                  <div className="text-xs text-primary-300">
                    Connected since {new Date(lastConnected).toLocaleTimeString()}
                  </div>
                )}
                {shouldShowReconnect && (
                  <div className="mt-2 space-y-2">
                    {connectionStatus === 'error' && xmtpError && (
                      <div className="text-xs text-red-400 bg-red-500/10 rounded p-2">
                        {xmtpError}
                      </div>
                    )}
                    {connectionStatus === 'disconnected' && (
                      <div className="text-xs text-primary-300">
                        Not connected to the XMTP network. Messages won't sync until reconnected.
                      </div>
                    )}
                    {walletNeedsReconnect && (
                      <div className="text-xs text-yellow-400">
                        Wallet not connected. Please reconnect your wallet to sign in.
                      </div>
                    )}
                    {connectError && (
                      <div className="text-xs text-red-400 bg-red-500/10 rounded p-2">
                        {connectError}
                      </div>
                    )}
                    <button
                      onClick={() => {
                        void handleReconnect();
                      }}
                      disabled={isReconnecting || !identity}
                      className="btn-primary text-xs disabled:opacity-50"
                    >
                      {isReconnecting ? 'Connecting...' : connectionStatus === 'error' ? 'Retry Connection' : 'Connect'}
                    </button>
                    {showConnectorList && (
                      <div className="space-y-2">
                        <div className="text-xs text-primary-300">Choose a wallet to reconnect:</div>
                        <div className="space-y-2">
                          {walletOptions.map((option) => (
                              <button
                                key={option.id}
                                onClick={async () => {
                                  try {
                                    setConnectError(null);
                                    const connected = await connectWallet(option);
                                    const connectedAddress = connected?.accounts?.[0];
                                    if (!connectedAddress || !connected?.signMessage) {
                                      throw new Error(
                                        'The wallet connected without an account-bound signer. Reconnect it and retry.'
                                      );
                                    }
                                    await handleReconnect({
                                      address: connectedAddress,
                                      chainId: connected.chainId,
                                      signMessage: connected.signMessage,
                                    });
                                  } catch (err) {
                                    setConnectError(formatWalletConnectionError(err));
                                  }
                                }}
                                className="w-full p-4 bg-primary-950/60 hover:bg-primary-900 border border-primary-800/60 hover:border-accent-400 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-left"
                                disabled={isReconnecting || option.disabled}
                              >
                                <div className="flex items-center gap-3">
                                  <span className="text-3xl">{option.icon}</span>
                                  <div>
                                    <div className="text-sm font-medium text-primary-50">{option.name}</div>
                                    {option.description && (
                                      <div className="text-xs text-primary-300">{option.description}</div>
                                    )}
                                  </div>
                                </div>
                              </button>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
                {connectionStatus === 'connecting' && (
                  <div className="mt-2 text-xs text-primary-200">
                    <div className="flex items-center gap-2">
                      <svg className="animate-spin h-3 w-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                      </svg>
                      <span>Registering identity on XMTP network...</span>
                    </div>
                    <div className="mt-1 text-primary-300">
                      Check the <button onClick={() => navigate('/debug')} className="underline hover:text-primary-200">Debug tab</button> for details
                    </div>
                  </div>
                )}
              </div>

              {/* Current Identity */}
              <div className="p-4">
                <div className="flex items-center justify-between mb-1">
                  <div className="font-medium">Current Identity</div>
                  <button
                    onClick={() => setShowQR(true)}
                    className="flex items-center gap-1 text-sm text-accent-300 hover:text-accent-200 transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
                    </svg>
                    Show QR Code
                  </button>
                </div>
                <div className="text-sm text-primary-200 mb-2">Ethereum Address</div>
                <div className="font-mono text-sm bg-primary-950/20 rounded px-3 py-2 break-all">
                  {identity?.address}
                </div>
                <div className="mt-2 text-xs text-primary-300">
                  This local account key signs Converge messages. Export is available under Advanced.
                </div>
              </div>

              {/* Add this browser to an existing inbox */}
              <button
                onClick={handleAddIdentity}
                className="w-full p-4 text-left hover:bg-primary-950/60 transition-colors flex items-center justify-between"
              >
                <div>
                  <div className="font-medium">Add This Device to Existing Inbox</div>
                  <div className="text-sm text-primary-200">Create a fresh local account key approved by a wallet that controls the inbox</div>
                </div>
                <svg className="w-5 h-5 text-primary-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
              </button>
            </div>
          </section>

          <FarcasterSettings />

          {/* Inbox Actions */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Inbox</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <button
                onClick={handleBurnInbox}
                disabled={isBurningInbox || !identity?.inboxId}
                className="w-full p-4 text-left hover:bg-primary-950/60 transition-colors flex items-center justify-between text-red-400 disabled:opacity-50"
              >
                <div>
                  <div className="font-medium">{isBurningInbox ? 'Burning Inbox...' : 'Burn Inbox'}</div>
                  <div className="text-sm text-primary-200">Revoke this installation when possible, then wipe this inbox from the browser</div>
                </div>
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
                  />
                </svg>
              </button>
            </div>
          </section>

          {/* Privacy & Security */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Privacy & Security</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Message Encryption</div>
                    <div className="text-sm text-primary-200">End-to-end encryption via XMTP</div>
                  </div>
                  <span className="text-sm text-green-500">✓ Enabled</span>
                </div>
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Local Storage</div>
                    <div className="text-sm text-primary-200">Private keys, recovery phrases, and decrypted app data are stored unencrypted in this browser</div>
                  </div>
                  <span className="text-sm text-amber-300">Local only</span>
                </div>
              </div>
            </div>
          </section>

          {/* Data Management */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Data Management</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <div className="font-medium">Storage Usage</div>
                    <div className="text-sm text-primary-200">Local database size</div>
                  </div>
                  {storageSize !== null && (
                    <span className="text-sm text-primary-100">{formatBytes(storageSize)}</span>
                  )}
                </div>
                <button
                  onClick={loadStorageSize}
                  disabled={isLoadingSize}
                  className="text-sm text-accent-300 hover:text-accent-200"
                >
                  {isLoadingSize ? 'Calculating...' : 'Calculate Size'}
                </button>
              </div>

              <button
                onClick={handleClearCache}
                className="w-full p-4 text-left hover:bg-primary-950/60 transition-colors flex items-center justify-between"
              >
                <div>
                  <div className="font-medium">Clear App Cache</div>
                  <div className="text-sm text-primary-200">Force refresh from server</div>
                </div>
                <svg className="w-5 h-5 text-primary-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                  />
                </svg>
              </button>

            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Advanced</h2>
            <details className="bg-primary-900/60 border border-primary-800/60 rounded-lg backdrop-blur">
              <summary className="cursor-pointer p-4 font-medium text-primary-100">
                Key export and full reset
              </summary>
              <div className="border-t border-primary-800/60 divide-y divide-primary-800/60">
                <button
                  onClick={handleDownloadKeyfile}
                  disabled={!canDownloadKeyfile}
                  className="w-full p-4 text-left flex items-center justify-between transition-colors hover:bg-primary-950/60 disabled:cursor-not-allowed disabled:text-primary-400"
                >
                  <div>
                    <div className="font-medium">Download keyfile</div>
                    <div className="text-sm text-primary-200">
                      {canDownloadKeyfile
                        ? 'Exports the unencrypted local account key'
                        : 'No exportable local account key is available'}
                    </div>
                  </div>
                  <svg className="w-5 h-5 text-primary-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5m0 0l5-5m-5 5V4" />
                  </svg>
                </button>
                <button
                  onClick={handleClearData}
                  className="w-full p-4 text-left hover:bg-primary-950/60 transition-colors flex items-center justify-between text-red-400"
                >
                  <div>
                    <div className="font-medium">Clear All Browser Data</div>
                    <div className="text-sm text-primary-200">Remove every Converge inbox and local database without remote revocation</div>
                  </div>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                </button>
              </div>
            </details>
          </section>

          {/* App */}
          <section>
            <h2 className="text-lg font-semibold mb-3">App</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Notifications</div>
                    <div className="text-sm text-primary-200">{pushDescription}</div>
                  </div>
                  {pushStatus !== 'unsupported' && (
                    <button
                      type="button"
                      role="switch"
                      aria-checked={pushIsOn}
                      aria-label={pushIsOn ? 'Disable notifications' : 'Enable notifications'}
                      onClick={pushIsOn ? handleDisablePush : handleEnablePush}
                      disabled={
                        isPushLoading ||
                        pushStatus === 'unknown' ||
                        (!pushIsOn && pushPreparation === 'preparing')
                      }
                      className={`relative h-6 w-11 flex-shrink-0 rounded-full transition-colors disabled:opacity-50 ${
                        pushIsOn ? 'bg-accent-500' : 'bg-primary-700'
                      }`}
                    >
                      <span
                        className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-transform ${
                          pushIsOn ? 'translate-x-5' : 'translate-x-0.5'
                        }`}
                      />
                    </button>
                  )}
                </div>
                {pushFeedback && (
                  <div
                    role={pushFeedback.tone === 'error' ? 'alert' : 'status'}
                    className={`mt-3 text-sm ${
                      pushFeedback.tone === 'error'
                        ? 'text-red-300'
                        : pushFeedback.tone === 'success'
                          ? 'text-green-300'
                          : 'text-primary-200'
                    }`}
                  >
                    {pushFeedback.message}
                  </div>
                )}
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Install App</div>
                    <div className="text-sm text-primary-200">
                      Add Converge to your home screen for quick access
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      // Trigger install prompt via beforeinstallprompt event
                      // The browser will handle this natively
                      const nav = navigator as { standalone?: boolean };
                      if ('standalone' in navigator && !nav.standalone) {
                        // iOS Safari - show instructions
                        alert('To install:\n1. Tap the Share button\n2. Tap "Add to Home Screen"');
                      } else {
                        // Android Chrome and others - browser will show native prompt
                        alert('Use your browser\'s "Add to Home Screen" or "Install" option to install the app.');
                      }
                    }}
                    className="btn-primary text-sm"
                  >
                    Install
                  </button>
                </div>
              </div>
            </div>
          </section>

          {/* XMTP Installations */}
          <InstallationsSettings />

          {/* About */}
          <section>
            <h2 className="text-lg font-semibold mb-3">About</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <span className="text-primary-200">Version</span>
                  <span>{buildInfo.version}</span>
                </div>
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <span className="text-primary-200">Protocol</span>
                  <span>XMTP protocol v3 (SDK v6.1.2)</span>
                </div>
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <span className="text-primary-200">Storage</span>
                  <span>IndexedDB (Dexie)</span>
                </div>
              </div>
              <div className="p-4">
                <a
                  href="https://github.com/pierce403/converge.cv"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-between text-accent-300 hover:text-accent-200"
                >
                  <span>View on GitHub</span>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                </a>
              </div>
            </div>
          </section>

          {/* Footer info */}
          <div className="text-center text-sm text-primary-300 pb-8">
            <p>Converge - Local-first XMTP messaging</p>
            <p className="mt-1">End-to-end encrypted · No server storage</p>
          </div>
        </div>
      </div>

      {/* QR Code Overlay */}
      {showQR && identity && (
        <QRCodeOverlay address={identity.address} onClose={() => setShowQR(false)} />
      )}

      {showAddIdentityModal && (
        <ConnectExistingInboxModal
          error={addIdentityError}
          isWorking={isAddingIdentity}
          onClose={() => setShowAddIdentityModal(false)}
          onError={setAddIdentityError}
          onWorkingChange={setIsAddingIdentity}
          onConnect={connectExistingWalletInbox}
          onRecoverInstallations={revokeOldInstallationsForExistingWalletInbox}
        />
      )}
    </div>
  );
}

interface ConnectExistingInboxModalProps {
  error: string | null;
  isWorking: boolean;
  onClose: () => void;
  onError: (message: string | null) => void;
  onWorkingChange: (value: boolean) => void;
  onConnect: (
    accounts: readonly string[] | undefined,
    signMessage?: WalletSignMessage,
    onStatus?: (message: string) => void,
    chainId?: number,
    walletType?: WalletTypeHint
  ) => Promise<void>;
  onRecoverInstallations: (
    accounts: readonly string[] | undefined,
    signMessage?: WalletSignMessage,
    options?: InstallationRecoveryOptions
  ) => Promise<InstallationRecoveryResult>;
}

function ConnectExistingInboxModal({
  error,
  isWorking,
  onClose,
  onError,
  onWorkingChange,
  onConnect,
  onRecoverInstallations,
}: ConnectExistingInboxModalProps) {
  const {
    connectWallet,
    walletOptions,
    isConnected,
    isConnecting,
    address,
    chainId,
    signMessage,
  } = useWalletConnection();
  const [lastAccounts, setLastAccounts] = useState<readonly string[] | undefined>();
  const [walletSnapshot, setWalletSnapshot] = useState<{
    accounts: readonly string[];
    chainId?: number;
    signMessage: WalletSignMessage;
  } | null>(null);
  const [blockedInboxId, setBlockedInboxId] = useState<string | null>(null);
  const [recoveryNotice, setRecoveryNotice] = useState<string | null>(null);
  const [recoveryStep, setRecoveryStep] = useState<string | null>(null);
  const [connectionStep, setConnectionStep] = useState<string | null>(null);
  const [activeAction, setActiveAction] = useState<'wallet' | 'connect' | 'recover' | null>(null);
  const [associationAcknowledged, setAssociationAcknowledged] = useState(false);
  const [walletTypeHint, setWalletTypeHint] = useState<WalletTypeHint | undefined>();
  const [needsWalletTypeChoice, setNeedsWalletTypeChoice] = useState(false);
  const inboxWalletOptions = getInboxConnectionWalletOptions(walletOptions);
  const errorInboxId = extractInstallationLimitInboxId(error);
  const recoveryInboxId = blockedInboxId ?? errorInboxId;
  const isRecovering = activeAction === 'recover';
  const isConnectingExistingInbox = activeAction === 'connect';
  const isConnectingWallet = activeAction === 'wallet';
  const legacyScwRecoveryBlocked = isLegacyScwChainZeroRecoveryError(error);
  const showInstallationRecovery = !legacyScwRecoveryBlocked && (
    isInstallationLimitError(error) ||
    isStaleSetupInstallationError(error) ||
    Boolean(recoveryInboxId) ||
    isRecovering
  );
  const connectedAccounts = walletSnapshot?.accounts?.length
    ? walletSnapshot.accounts
    : address
      ? [address]
      : undefined;
  const connectedSigner = walletSnapshot?.signMessage ?? signMessage;
  const connectedChainId = walletSnapshot?.chainId ?? chainId;

  const runConnect = async (
    getAccounts: () => Promise<readonly string[] | undefined>,
    explicitWalletType = walletTypeHint
  ) => {
    if (isWorking) return;
    if (!associationAcknowledged) {
      onError('Acknowledge the public wallet-to-inbox identity link before continuing.');
      return;
    }
    setActiveAction('connect');
    setNeedsWalletTypeChoice(false);
    onWorkingChange(true);
    onError(null);
    setRecoveryNotice(null);
    setRecoveryStep(null);
    setConnectionStep('Checking the connected wallet…');
    try {
      if (!connectedSigner) {
        throw new Error('Wallet signing is not available. Connect your wallet and try again.');
      }
      const accounts = await getAccounts();
      if (accounts?.length) {
        setLastAccounts(accounts);
      }
      await onConnect(
        accounts,
        connectedSigner,
        setConnectionStep,
        connectedChainId,
        explicitWalletType
      );
      onClose();
    } catch (err) {
      if (isWalletInspectionRequiredError(err)) {
        setWalletTypeHint(undefined);
        setNeedsWalletTypeChoice(true);
      }
      const message = err instanceof Error ? err.message : 'Failed to connect wallet';
      const inboxId = extractInstallationLimitInboxId(message);
      if (isLegacyScwChainZeroRecoveryError(message)) {
        setBlockedInboxId(null);
      }
      if (inboxId) {
        setBlockedInboxId(inboxId);
        setRecoveryStep(
          isStaleSetupInstallationError(message)
            ? `Inbox ${shortInboxId(inboxId)} has an interrupted setup installation. Remove it before retrying.`
            : `Inbox ${shortInboxId(inboxId)} is full. Use recovery before retrying.`
        );
      }
      onError(message);
    } finally {
      setConnectionStep(null);
      setActiveAction(null);
      onWorkingChange(false);
    }
  };

  const runWalletConnection = async (option: (typeof inboxWalletOptions)[number]) => {
    if (isWorking || isConnecting) return;
    setActiveAction('wallet');
    onWorkingChange(true);
    onError(null);
    setConnectionStep('Opening wallet connection…');
    try {
      const result = await connectWallet(option);
      const accounts = result?.accounts?.[0] ? [result.accounts[0]] : undefined;
      if (!accounts?.length) {
        throw new Error('The wallet connected without returning an account. Try again.');
      }
      if (!result?.signMessage) {
        throw new Error(
          'The wallet connected without an account-bound signer. Reconnect it and retry.'
        );
      }
      setLastAccounts(accounts);
      setWalletSnapshot({
        accounts,
        chainId: result.chainId,
        signMessage: result.signMessage,
      });
      setWalletTypeHint(undefined);
      setNeedsWalletTypeChoice(false);
      setAssociationAcknowledged(false);
      setConnectionStep(null);
    } catch (error) {
      onError(error instanceof Error ? error.message : 'Failed to connect wallet');
      setConnectionStep(null);
    } finally {
      setActiveAction(null);
      onWorkingChange(false);
    }
  };

  const runRecoverInstallations = async () => {
    if (isWorking) return;
    const accounts = lastAccounts?.length ? lastAccounts : connectedAccounts;
    if (!accounts?.length) {
      onError('Connect the wallet that owns the full inbox before revoking installations.');
      return;
    }
    if (!connectedSigner) {
      onError('Wallet signing is not available. Connect your wallet and try again.');
      return;
    }
    if (
      !window.confirm(
        isStaleSetupInstallationError(error)
          ? 'Remove the interrupted XMTP installation that no longer exists in this browser?'
          : 'Revoke the oldest XMTP installation for this wallet inbox to free one slot for Converge? That device may stop receiving messages.'
      )
    ) {
      return;
    }

    setActiveAction('recover');
    onWorkingChange(true);
    onError(null);
    setRecoveryNotice(null);
    setRecoveryStep(recoveryInboxId ? `Fetching installations for inbox ${shortInboxId(recoveryInboxId)}...` : 'Resolving wallet inbox...');
    try {
      console.info('[Settings] User started existing inbox installation recovery', {
        accounts,
        inboxId: recoveryInboxId,
      });
      const result = await onRecoverInstallations(accounts, connectedSigner, {
        inboxId: recoveryInboxId ?? undefined,
        chainId: connectedChainId,
        walletType: walletTypeHint,
        onStatus: setRecoveryStep,
      });
      const count = result.revoked.length || 1;
      const recoveredInboxId = result.inboxId ?? recoveryInboxId;
      setRecoveryNotice(
        `Revoked ${count} installation${count === 1 ? '' : 's'}${recoveredInboxId ? ` from inbox ${shortInboxId(recoveredInboxId)}` : ''}. Try "Approve This Device" again.`
      );
      setRecoveryStep(null);
      setBlockedInboxId(null);
      console.info('[Settings] Existing inbox installation recovery completed', result);
    } catch (err) {
      setRecoveryStep(null);
      const message = err instanceof Error ? err.message : 'Failed to revoke old installations';
      if (isLegacyScwChainZeroRecoveryError(message)) {
        setBlockedInboxId(null);
      }
      onError(message);
    } finally {
      setActiveAction(null);
      onWorkingChange(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
      <div className="w-full max-w-lg rounded-xl border border-primary-800/60 bg-primary-950 shadow-2xl">
        <div className="p-4 border-b border-primary-800/60 flex items-center justify-between">
          <div>
            <div className="text-lg font-semibold text-primary-50">Add This Device</div>
            <div className="text-sm text-primary-200">
              Use a wallet that already controls the XMTP inbox to approve this browser.
            </div>
          </div>
          <button
            onClick={() => {
              if (isWorking) return;
              onClose();
            }}
            className="text-primary-300 hover:text-primary-100 transition-colors"
            aria-label="Close"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="p-4 space-y-3">
          <p className="text-sm text-primary-200">
            Converge generates a fresh local account key, registers or reuses one browser installation in the target inbox, and keeps your current inbox unchanged. It will not move a registered key; reassignment would strand that key&apos;s previous inbox.
          </p>

          <div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-100">
            Wallet and account addresses associated with an XMTP inbox are publicly queryable. This identity link is effectively permanent in XMTP history.
          </div>

          {error && (
            <div className="text-xs text-red-400 bg-red-500/10 rounded p-2">
              {error}
            </div>
          )}

          {needsWalletTypeChoice && connectedAccounts?.length && (
            <div className="space-y-2 rounded-lg border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-100">
              <div className="font-medium">What kind of wallet is this?</div>
              <div className="text-xs text-amber-100/90">
                Converge could not inspect the account, so choose its wallet type to continue.
              </div>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  className="btn-secondary px-3 py-2 text-xs"
                  onClick={() => {
                    setWalletTypeHint('EOA');
                    void runConnect(async () => connectedAccounts, 'EOA');
                  }}
                >
                  Regular wallet
                </button>
                <button
                  type="button"
                  className="btn-secondary px-3 py-2 text-xs disabled:opacity-50"
                  disabled={
                    !Number.isSafeInteger(connectedChainId) ||
                    (connectedChainId ?? 0) <= 0
                  }
                  title={
                    !Number.isSafeInteger(connectedChainId) ||
                    (connectedChainId ?? 0) <= 0
                      ? 'Reconnect the smart account on its network first.'
                      : undefined
                  }
                  onClick={() => {
                    setWalletTypeHint('SCW');
                    void runConnect(async () => connectedAccounts, 'SCW');
                  }}
                >
                  Smart account (such as Base app)
                </button>
              </div>
            </div>
          )}

          {recoveryNotice && (
            <div className="text-xs text-emerald-200 bg-emerald-500/10 border border-emerald-500/30 rounded p-2">
              {recoveryNotice}
            </div>
          )}

          {connectionStep && (
            <div className="text-xs text-primary-200 bg-primary-900/60 border border-primary-700 rounded p-2">
              {connectionStep}
            </div>
          )}

          {showInstallationRecovery && (
            <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/10 p-3 text-sm text-yellow-100 space-y-2">
              <div>
                {isStaleSetupInstallationError(error)
                  ? 'An interrupted setup installation is still registered. Remove that exact installation, then retry approval.'
                  : 'This inbox is full. Click recovery first, approve the wallet signature, then retry the connection.'}
              </div>
              {recoveryInboxId && (
                <div className="font-mono text-xs text-yellow-50/90 break-all">
                  Inbox {recoveryInboxId}
                </div>
              )}
              {recoveryStep && (
                <div className="text-xs text-yellow-50/90">
                  {recoveryStep}
                </div>
              )}
              <button
                onClick={runRecoverInstallations}
                disabled={isWorking || !connectedSigner}
                className="btn-secondary text-sm px-3 py-2 disabled:opacity-50"
                title={!connectedSigner ? 'Wallet signing is not available yet.' : undefined}
              >
                {isRecovering
                  ? 'Revoking...'
                  : isStaleSetupInstallationError(error)
                    ? 'Remove Interrupted Installation'
                    : 'Revoke Oldest Installation'}
              </button>
            </div>
          )}

          {(walletSnapshot || (isConnected && address)) && connectedAccounts?.[0] && (
            <div className="rounded-lg border border-primary-800/60 bg-primary-900/50 p-3">
              <div className="text-xs text-primary-300 mb-1">Connected wallet</div>
              <div className="font-mono text-xs text-primary-100 break-all">
                {connectedAccounts[0]}
              </div>
              <label className="mt-3 flex items-start gap-2 text-xs text-primary-200">
                <input
                  type="checkbox"
                  className="mt-0.5 form-checkbox rounded text-accent-500"
                  checked={associationAcknowledged}
                  onChange={(event) => setAssociationAcknowledged(event.target.checked)}
                />
                <span>I understand this wallet-to-inbox association is public and effectively permanent.</span>
              </label>
              <div className="mt-2">
                <button
                  onClick={() => runConnect(async () => connectedAccounts)}
                  disabled={isWorking || !associationAcknowledged}
                  className="btn-primary text-sm px-3 py-2 disabled:opacity-50"
                  title={!associationAcknowledged ? 'Acknowledge the public identity link to continue.' : undefined}
                >
                  {isConnectingExistingInbox ? 'Adding device...' : 'Approve This Device'}
                </button>
              </div>
            </div>
          )}

          <div className="text-sm text-primary-200">Connect with:</div>
          <div className="flex flex-wrap gap-2">
            {inboxWalletOptions.map((option) => (
              <button
                key={option.id}
                onClick={() => runWalletConnection(option)}
                disabled={isWorking || isConnecting || option.disabled}
                className="btn-secondary text-sm px-3 py-2 disabled:opacity-50"
              >
                {isConnectingWallet || isConnecting ? 'Connecting...' : option.name}
              </button>
            ))}
          </div>

          {inboxWalletOptions.length === 0 && (
            <div className="text-xs text-primary-300 rounded p-2 bg-primary-900/50 border border-primary-800/60">
              No WalletConnect or browser wallet connectors are available in this browser.
            </div>
          )}

          <div className="flex items-center justify-end gap-2 pt-2">
            <button
              onClick={onClose}
              disabled={isWorking}
              className="btn-secondary text-sm px-3 py-2 disabled:opacity-50"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
