/**
 * Settings page
 */

import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/features/auth';
import { getStorage } from '@/lib/storage';
import { useXmtpStore } from '@/lib/stores/xmtp-store';
import { getXmtpClient } from '@/lib/xmtp';
import { InstallationsSettings } from './InstallationsSettings';
import { useWalletConnection } from '@/lib/wagmi';
import { QRCodeOverlay } from '@/components/QRCodeOverlay';
import {
  disablePush,
  enablePushForCurrentUser,
  getAppPushStatus,
  getPushPermissionStatus,
  preparePushBrowserResources,
  type AppPushStatus,
} from '@/lib/push';
import { exportIdentityToKeyfile, serializeKeyfile } from '@/lib/keyfile';
import { isAutoGeneratedDisplayName, suggestAnimalDisplayName } from '@/lib/identity/profile-suggestions';
import { useAuthStore } from '@/lib/stores/auth-store';
import { useInboxRegistryStore } from '@/lib/stores/inbox-registry-store';
import { resolveENSAvatar, resolveENSFromAddress } from '@/lib/utils/ens';
import { updatePushInboxProfile } from '@/lib/push';
import { formatWalletConnectionError } from '@/features/auth/wallet-connection-error';
import { ethereumAddressesEqual } from '@/lib/utils/ethereum';
import buildInfo from '@/build-info.json';
import { getInstallationRecoveryView } from './installation-recovery-view';
import { clearAllBrowserData } from '@/lib/identity/clear-browser-data';

interface ConnectedWalletSnapshot {
  address: string;
  chainId?: number;
  signMessage: (message: string) => Promise<string>;
}

function installationRepairSuccessNotice(result: {
  previousInstallationId?: string;
  previousInstallationAbsent: boolean;
  previousInstallationRevoked: boolean;
}): string {
  if (
    result.previousInstallationId &&
    !result.previousInstallationAbsent &&
    !result.previousInstallationRevoked
  ) {
    return 'This browser installation was repaired and recovered from the same local database after reopening. The prior installation remains on the inbox ledger and can be revoked later.';
  }
  return 'This browser installation was repaired and recovered from the same local database after reopening.';
}

export function SettingsPage() {
  const navigate = useNavigate();
  const {
    identity,
    burnIdentity,
    reconnectCurrentIdentity,
    repairCurrentInstallation,
  } = useAuth();
  const {
    connectionStatus,
    lastConnected,
    error: xmtpError,
    installationRecovery,
  } = useXmtpStore();
  const [storageSize, setStorageSize] = useState<number | null>(null);
  const [isLoadingSize, setIsLoadingSize] = useState(false);
  const [isEditingName, setIsEditingName] = useState(false);
  const [profileRefreshSource, setProfileRefreshSource] = useState<'ens' | null>(null);
  const [profileRefreshFeedback, setProfileRefreshFeedback] = useState<string | null>(null);
  const computeInitialDisplayName = () => {
    const raw = identity?.displayName?.trim();
    if (!raw || isAutoGeneratedDisplayName(raw)) {
      const seed = identity?.inboxId || identity?.address;
      return suggestAnimalDisplayName(seed).displayName;
    }
    return raw;
  };

  const [displayName, setDisplayName] = useState<string>(computeInitialDisplayName());
  const avatarInputRef = useRef<HTMLInputElement>(null);
  const {
    disconnectWallet,
    connectWallet,
    walletOptions,
    isConnected: isWalletConnected,
    address: walletAddress,
    chainId: connectedWalletChainId,
    signMessage,
  } = useWalletConnection();
  const [showQR, setShowQR] = useState(false);
  // Track push status
  const [pushStatus, setPushStatus] = useState<'unknown' | AppPushStatus['state']>('unknown');
  const [pushDetails, setPushDetails] = useState<AppPushStatus | null>(null);
  const [isPushLoading, setIsPushLoading] = useState(false);
  const [pushPreparation, setPushPreparation] = useState<'preparing' | 'ready' | 'retry'>('preparing');
  const [pushFeedback, setPushFeedback] = useState<{
    tone: 'info' | 'success' | 'error';
    message: string;
  } | null>(null);
  const [activeConnectionAction, setActiveConnectionAction] = useState<
    'reconnect' | 'repair' | null
  >(null);
  const isReconnecting = activeConnectionAction !== null;
  const [connectError, setConnectError] = useState<string | null>(null);
  const [connectNotice, setConnectNotice] = useState<string | null>(null);
  const [showConnectorList, setShowConnectorList] = useState(false);
  const [pendingWalletAction, setPendingWalletAction] = useState<'reconnect' | 'repair'>(
    'reconnect'
  );
  const [isBurningInbox, setIsBurningInbox] = useState(false);
  const canDownloadKeyfile = Boolean(identity?.privateKey || identity?.mnemonic);

  const handleConnectionAction = async (
    action: 'reconnect' | 'repair',
    connectedWallet?: ConnectedWalletSnapshot,
    repairConfirmed = false
  ) => {
    if (!identity || isReconnecting) return;

    if (action === 'repair' && !installationRecovery) {
      setConnectError('Retry the saved installation first so Converge can inspect it safely.');
      return;
    }
    if (
      action === 'repair' &&
      !repairConfirmed &&
      !window.confirm(
        `Repair this browser's XMTP installation?\n\n${installationRepairOutcome ?? 'Converge will preserve local messages and repair the saved local XMTP database.'}\n\nConverge keeps one repair connection open through any required registration. Before reporting success, it closes that connection, reopens the same local database, and verifies the exact same installation. An interrupted unregistered attempt may open a different installation ID, so Converge first rechecks the inbox ledger. No arbitrary device will be revoked. An older installation may need to be online to restore encrypted history.`
      )
    ) {
      return;
    }

    setActiveConnectionAction(action);
    try {
      setConnectError(null);
      setConnectNotice(null);
      setShowConnectorList(false);
      // If identity has a private key (Converge-generated), use it directly
      if (identity.privateKey) {
        if (action === 'repair') {
          const result = await repairCurrentInstallation();
          setConnectNotice(installationRepairSuccessNotice(result));
        } else {
          await reconnectCurrentIdentity();
        }
        return;
      }

      // For wallet-connected identities, ensure the wallet is connected to the right address
      const walletSnapshot = connectedWallet;
      const effectiveWallet = walletSnapshot?.address ?? walletAddress;
      try {
        if (
          !walletSnapshot &&
          (!isWalletConnected || !ethereumAddressesEqual(effectiveWallet, identity.address))
        ) {
          setPendingWalletAction(action);
          setShowConnectorList(true);
          setConnectError(
            effectiveWallet && !ethereumAddressesEqual(effectiveWallet, identity.address)
              ? 'Please connect the wallet that owns this identity to continue.'
              : 'Choose a wallet to reconnect.'
          );
          return;
        }
      } catch (connectErr) {
        console.error('Wallet connection failed:', connectErr);
        setConnectError(formatWalletConnectionError(connectErr));
        setShowConnectorList(true);
        return;
      }

      if (!ethereumAddressesEqual(effectiveWallet, identity.address)) {
        throw new Error('Please connect the wallet that owns this identity to continue.');
      }

      const effectiveSignMessage = walletSnapshot?.signMessage ?? signMessage;
      if (!effectiveSignMessage) {
        throw new Error('Wallet signing is not available. Try reconnecting your wallet.');
      }

      const reconnectOptions = {
        chainId: walletSnapshot?.chainId ?? connectedWalletChainId,
        walletType: identity.walletType,
        signMessage: async (message: string) =>
          walletSnapshot
            ? await effectiveSignMessage(message)
            : await effectiveSignMessage(message, identity.address),
      };
      if (action === 'repair') {
        const result = await repairCurrentInstallation(reconnectOptions);
        setConnectNotice(installationRepairSuccessNotice(result));
      } else {
        await reconnectCurrentIdentity(reconnectOptions);
      }
    } catch (error) {
      console.error(`${action === 'repair' ? 'Installation repair' : 'Reconnect'} failed:`, error);
      if (!showConnectorList && !isWalletConnected) {
        setPendingWalletAction(action);
        setShowConnectorList(true);
      }
      setConnectError(error instanceof Error ? error.message : 'Failed to reconnect wallet');
    } finally {
      setActiveConnectionAction(null);
    }
  };

  // Check push status on mount
  useEffect(() => {
    const checkPushStatus = async () => {
      const permission = getPushPermissionStatus();
      if (permission === 'unsupported') {
        setPushStatus('unsupported');
        return;
      }
      const status = await getAppPushStatus();
      setPushDetails(status);
      setPushStatus(status.state);
    };
    checkPushStatus();
    if (getPushPermissionStatus() !== 'unsupported') {
      void preparePushBrowserResources()
        .then(() => setPushPreparation('ready'))
        .catch(() => setPushPreparation('retry'));
    }
  }, []);

  const handleEnablePush = async () => {
    if (isPushLoading) return;
    setIsPushLoading(true);
    setPushFeedback(null);
    try {
      if (pushPreparation !== 'ready') {
        setPushPreparation('preparing');
        try {
          await preparePushBrowserResources();
          setPushPreparation('ready');
        } catch (error) {
          setPushPreparation('retry');
          setPushFeedback({
            tone: 'error',
            message: `Unable to prepare notifications: ${error instanceof Error ? error.message : 'Unknown error'}`,
          });
          return;
        }
      }
      const result = await enablePushForCurrentUser();

      if (result.success) {
        const status = await getAppPushStatus();
        setPushDetails(status);
        setPushStatus(status.state);
        setPushFeedback({
          tone: status.state === 'enabled' ? 'success' : 'info',
          message:
            status.state === 'enabled'
              ? 'Notifications are on for this inbox.'
              : 'Notifications are on, but registration will retry automatically when the app is online.',
        });
      } else {
        const status = await getAppPushStatus();
        setPushDetails(status);
        setPushStatus(status.state);
        setPushFeedback({
          tone: 'error',
          message: result.error || 'Failed to enable notifications.',
        });
      }
    } catch (e) {
      console.warn('[Settings] Enable push failed', e);
      setPushFeedback({
        tone: 'error',
        message: e instanceof Error ? e.message : 'Failed to enable notifications.',
      });
    } finally {
      setIsPushLoading(false);
    }
  };

  const handleDisablePush = async () => {
    if (isPushLoading) return;
    setIsPushLoading(true);
    setPushFeedback(null);
    try {
      const success = await disablePush();
      const status = await getAppPushStatus();
      setPushDetails(status);
      setPushStatus(status.state);
      if (success && status.pendingDeletionCount === 0) {
        setPushFeedback({ tone: 'success', message: 'Notifications disabled.' });
      } else if (status.pendingDeletionCount > 0) {
        setPushFeedback({
          tone: 'error',
          message: `Browser notifications are off, but ${status.pendingDeletionCount} relay registration${status.pendingDeletionCount === 1 ? '' : 's'} could not be deleted. Retry this toggle when online.`,
        });
      } else {
        setPushFeedback({ tone: 'error', message: 'Failed to disable notifications.' });
      }
    } catch (e) {
      console.warn('[Settings] Disable push failed', e);
      setPushFeedback({
        tone: 'error',
        message: e instanceof Error ? e.message : 'Failed to disable notifications.',
      });
    } finally {
      setIsPushLoading(false);
    }
  };

  const handleBurnInbox = async () => {
    if (!identity?.inboxId || isBurningInbox) return;
    const label = identity.displayName?.trim() || 'this inbox';
    if (!confirm(`Burn ${label}? This removes its key, messages, contacts, profile, attachments, and local XMTP database from this browser.`)) {
      return;
    }

    setIsBurningInbox(true);
    try {
      const result = await burnIdentity(identity.inboxId);
      if (!result.localDataRemoved) {
        alert(
          `Burn Inbox could not finish the local wipe. The inbox key and switcher entry were kept so you can retry. Close other Converge tabs, then try again.\n\n${result.localCleanupWarnings.join('\n')}`
        );
        setIsBurningInbox(false);
        return;
      }
      try {
        await disconnectWallet();
      } catch (error) {
        console.warn('[Settings] Wallet disconnect after Burn Inbox failed (non-fatal):', error);
      }

      const warnings = [
        result.pushWarning,
        result.revokeWarning,
        ...result.localCleanupWarnings,
      ].filter((message): message is string => Boolean(message));
      if (warnings.length > 0) {
        alert(`Inbox data removal completed with warnings:\n\n${warnings.join('\n')}`);
      }

      window.location.assign(result.intentionallyEmpty ? '/onboarding' : '/');
    } catch (error) {
      console.error('Failed to burn inbox:', error);
      alert(error instanceof Error ? error.message : 'Failed to burn inbox');
      setIsBurningInbox(false);
    }
  };

  const handleAvatarChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Check file size (max 256KB to keep XMTP messages small)
    if (file.size > 256 * 1024) {
      alert('Avatar image must be less than 256KB');
      return;
    }

    // Check file type
    if (!file.type.startsWith('image/')) {
      alert('Please select an image file');
      return;
    }

    try {
      // Convert to data URI
      const reader = new FileReader();
      reader.onload = async (event) => {
        const dataUri = event.target?.result as string;

        // Update identity with avatar
        if (identity) {
          const storage = await getStorage();
          const updatedIdentity = { ...identity, avatar: dataUri };
          await storage.putIdentity(updatedIdentity);

          // Persist to XMTP so it survives clear-all
          try {
            const xmtp = getXmtpClient();
            await xmtp.saveProfile(updatedIdentity.displayName, dataUri);
          } catch (err) {
            console.warn('[Settings] Failed to save avatar to network (non-fatal):', err);
          }

          window.location.reload(); // Refresh to show new avatar
        }
      };
      reader.readAsDataURL(file);
    } catch (error) {
      console.error('Failed to update avatar:', error);
      alert('Failed to update avatar');
    }
  };

  const handleSaveDisplayName = async () => {
    try {
      if (identity) {
        const storage = await getStorage();
        const updatedIdentity = { ...identity, displayName: displayName.trim() };
        await storage.putIdentity(updatedIdentity);
        // Persist to XMTP so it survives clear-all
        try {
          const xmtp = getXmtpClient();
          await xmtp.saveProfile(updatedIdentity.displayName, updatedIdentity.avatar);
        } catch (err) {
          console.warn('[Settings] Failed to save display name to network (non-fatal):', err);
        }
        setIsEditingName(false);
        window.location.reload(); // Refresh to show new name
      }
    } catch (error) {
      console.error('Failed to update display name:', error);
      alert('Failed to update display name');
    }
  };

  const persistRefreshedProfile = async (nextName: string, nextAvatar?: string) => {
    if (!identity) return;
    const currentIdentity = useAuthStore.getState().identity ?? identity;
    const updatedIdentity = {
      ...currentIdentity,
      displayName: nextName,
      avatar: nextAvatar?.trim() || currentIdentity.avatar,
    };
    await (await getStorage()).putIdentity(updatedIdentity);
    useAuthStore.getState().setIdentity(updatedIdentity);
    if (updatedIdentity.inboxId) {
      useInboxRegistryStore.getState().updateEntry(updatedIdentity.inboxId, {
        displayLabel: nextName,
        primaryDisplayIdentity: nextName,
        avatar: updatedIdentity.avatar,
      });
      await updatePushInboxProfile(updatedIdentity.inboxId, nextName);
    }
    setDisplayName(nextName);
    try {
      await getXmtpClient().saveProfile(nextName, updatedIdentity.avatar);
    } catch (error) {
      console.warn('[Settings] Failed to publish refreshed profile (non-fatal):', error);
    }
  };

  const profileLookupAddress = identity?.linkedWalletAddress || identity?.address;

  const handleRefreshEnsProfile = async () => {
    if (!profileLookupAddress || profileRefreshSource) return;
    setProfileRefreshSource('ens');
    setProfileRefreshFeedback(null);
    try {
      const name = await resolveENSFromAddress(profileLookupAddress);
      if (!name) {
        setProfileRefreshFeedback('No primary ENS name was found for the associated address.');
        return;
      }
      const avatar = await resolveENSAvatar(name);
      await persistRefreshedProfile(name, avatar ?? undefined);
      setProfileRefreshFeedback(`Profile refreshed from ${name}.`);
    } catch (error) {
      console.error('[Settings] ENS profile refresh failed:', error);
      setProfileRefreshFeedback('Could not refresh the ENS profile. Try again shortly.');
    } finally {
      setProfileRefreshSource(null);
    }
  };

  // Keep suggested name in sync when identity changes
  useEffect(() => {
    setDisplayName(computeInitialDisplayName());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [identity?.inboxId, identity?.address, identity?.displayName]);

  const handleDownloadKeyfile = () => {
    try {
      if (!identity) {
        alert('No identity is currently loaded.');
        return;
      }

      if (!identity.privateKey && !identity.mnemonic) {
        alert('This identity is managed by an external wallet. Connect on the device where it was generated to export a keyfile.');
        return;
      }
      if (
        !window.confirm(
          'This keyfile contains an unencrypted private key or recovery phrase. Anyone with the file can use this XMTP identity. Continue?'
        )
      ) {
        return;
      }

      const keyfile = exportIdentityToKeyfile(identity);
      const serialized = serializeKeyfile(keyfile);
      const blob = new Blob([serialized], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const safeAddress = identity.address.replace(/[^a-zA-Z0-9]/g, '').slice(0, 10) || 'identity';
      const timestamp = new Date().toISOString().replace(/[:]/g, '-');
      const filename = `converge-keyfile-${safeAddress}-${timestamp}.json`;

      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = filename;
      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to export keyfile:', error);
      alert('Failed to export keyfile. Please try again.');
    }
  };

  const handleClearData = async () => {
    if (
      confirm(
        'This will delete ALL your local data including messages, conversations, and XMTP databases. This action cannot be undone. Continue?'
      )
    ) {
      try {
        try {
          await Promise.race([
            disconnectWallet(),
            new Promise((resolve) => setTimeout(resolve, 1000)),
          ]);
          console.log('[Settings] Disconnected wallet via wagmi');
        } catch (e) {
          console.warn('[Settings] Wallet disconnect failed (non-fatal):', e);
        }
        await clearAllBrowserData();
      } catch (error) {
        console.error('Failed to clear data:', error);
        alert('Failed to clear data');
      }
    }
  };

  const loadStorageSize = async () => {
    setIsLoadingSize(true);
    try {
      const storage = await getStorage();
      const size = await storage.getStorageSize();
      setStorageSize(size);
    } catch (error) {
      console.error('Failed to load storage size:', error);
    } finally {
      setIsLoadingSize(false);
    }
  };

  const formatBytes = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  };

  const getConnectionStatusColor = () => {
    switch (connectionStatus) {
      case 'connected':
        return 'text-green-500';
      case 'connecting':
        return 'text-yellow-500';
      case 'error':
        return 'text-red-500';
      default:
        return 'text-primary-300';
    }
  };

  const getConnectionStatusText = () => {
    switch (connectionStatus) {
      case 'connected':
        return 'Connected';
      case 'connecting':
        return 'Connecting...';
      case 'error':
        return 'Connection Error';
      default:
        return 'Disconnected';
    }
  };

  const shouldShowReconnect = connectionStatus === 'error' || connectionStatus === 'disconnected';
  const walletNeedsReconnect = Boolean(identity && !identity.privateKey && !isWalletConnected);
  const hasLiveRepairCandidate = Boolean(
    identity?.installationRepairPending &&
      getXmtpClient().hasRetainedInstallationRepairClient()
  );
  const installationRecoveryView = installationRecovery
    ? getInstallationRecoveryView(installationRecovery, {
        installationRepairPending: identity?.installationRepairPending,
        stagedInstallationId: identity?.installationId,
        staleInstallationId: identity?.staleInstallationId,
        hasLiveRepairCandidate,
      })
    : null;
  const canRepairInstallation = installationRecoveryView?.canRepair === true;
  const installationRepairOutcome = installationRecoveryView?.outcome ?? null;
  const pushIsOn = pushDetails?.enabledPreference ?? pushStatus === 'enabled';
  const pushDescription = (() => {
    if (pushStatus === 'unsupported') return 'Not supported in this browser';
    if (pushStatus === 'unknown') return 'Checking notification status...';
    if (!pushIsOn && pushPreparation === 'preparing') return 'Preparing notification support...';
    if (pushStatus === 'partial') return 'Notifications will retry automatically when the app is online';
    if (pushStatus === 'enabled') return 'Notifications are on for this inbox';
    return 'Get notified about new messages';
  })();

  return (
    <div className="flex flex-col h-full text-primary-50">
      {/* Header */}
      <div className="bg-primary-950/70 border-b border-primary-800/60 p-4 backdrop-blur-md">
        <div className="flex items-center justify-between max-w-2xl mx-auto">
          <h1 className="text-xl font-semibold">Settings</h1>
          <button onClick={() => navigate('/')} className="text-primary-200 hover:text-primary-100">
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto bg-primary-950/20">
        <div className="max-w-2xl mx-auto p-4 space-y-6">

          {/* Profile Section */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Profile</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg p-4 space-y-4 backdrop-blur">
              {/* Avatar */}
              <div className="flex items-center gap-4">
                <div className="relative">
                  <div className="w-20 h-20 rounded-full bg-primary-950/60 border border-primary-800/60 flex items-center justify-center overflow-hidden">
                    {identity?.avatar ? (
                      <img src={identity.avatar} alt="Avatar" className="w-full h-full object-cover" />
                    ) : (
                      <svg className="w-10 h-10 text-primary-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                        />
                      </svg>
                    )}
                  </div>
                  <button
                    onClick={() => avatarInputRef.current?.click()}
                    className="absolute bottom-0 right-0 bg-accent-500 hover:bg-accent-600 rounded-full p-1.5 transition-colors shadow-lg"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"
                      />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                  </button>
                  <input
                    ref={avatarInputRef}
                    type="file"
                    accept="image/*"
                    onChange={handleAvatarChange}
                    className="hidden"
                  />
                </div>
                <div className="flex-1">
                  <div className="text-sm text-primary-200 mb-1">Avatar</div>
                  <div className="text-sm text-primary-300">Click camera icon to change</div>
                </div>
              </div>

              {/* Display Name */}
              <div>
                <label className="block text-sm font-medium text-primary-200 mb-2">Display Name (Optional)</label>
                {isEditingName ? (
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={displayName}
                      onChange={(e) => setDisplayName(e.target.value)}
                      placeholder="Enter display name"
                      className="flex-1 bg-primary-950/60 border border-primary-800/60 rounded-lg px-3 py-2 text-sm text-primary-100 focus:outline-none focus:ring-2 focus:ring-accent-400 focus:ring-offset-2 focus:ring-offset-primary-950"
                      maxLength={50}
                    />
                    <button onClick={handleSaveDisplayName} className="btn-primary text-sm px-3">
                      Save
                    </button>
                    <button
                      onClick={() => {
                        // Reset to suggested/actual value on cancel
                        const raw = identity?.displayName?.trim();
                        if (!raw || isAutoGeneratedDisplayName(raw)) {
                          const seed = identity?.inboxId || identity?.address;
                          setDisplayName(suggestAnimalDisplayName(seed).displayName);
                        } else {
                          setDisplayName(raw);
                        }
                        setIsEditingName(false);
                      }}
                      className="btn-secondary text-sm px-3"
                    >
                      Cancel
                    </button>
                  </div>
                ) : (
                  <div className="flex items-center justify-between">
                    <span className="text-sm">
                      {identity?.displayName || <span className="text-primary-300">Not set</span>}
                    </span>
                    <button
                      onClick={() => {
                        // Prefill with suggested name when entering edit if auto-label
                        const raw = identity?.displayName?.trim();
                        if (!raw || isAutoGeneratedDisplayName(raw)) {
                          const seed = identity?.inboxId || identity?.address;
                          setDisplayName(suggestAnimalDisplayName(seed).displayName);
                        }
                        setIsEditingName(true);
                      }}
                      className="text-sm text-accent-300 hover:text-accent-200"
                    >
                      Edit
                    </button>
                  </div>
                )}
              </div>
              <div className="border-t border-primary-800/60 pt-4">
                <div className="text-sm font-medium text-primary-200 mb-1">Refresh linked profile</div>
                <div className="text-sm text-primary-300 mb-3">
                  Replace this inbox name and avatar using the wallet address associated with it.
                </div>
                <div>
                  <button
                    type="button"
                    onClick={handleRefreshEnsProfile}
                    disabled={!profileLookupAddress || profileRefreshSource !== null}
                    className="btn-secondary text-sm px-3 disabled:opacity-50"
                  >
                    {profileRefreshSource === 'ens' ? 'Refreshing ENS…' : 'Refresh from ENS'}
                  </button>
                </div>
                {profileRefreshFeedback && (
                  <div className="mt-3 text-sm text-primary-200" role="status">
                    {profileRefreshFeedback}
                  </div>
                )}
              </div>
            </div>
          </section>

          {/* Identity & Connection */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Identity & Connection</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              {/* XMTP Connection Status */}
              <div className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex-1">
                    <div className="font-medium">XMTP Network</div>
                    <div className="text-sm text-primary-200">Connection status</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-full ${getConnectionStatusColor()}`} />
                    <span className={`text-sm font-medium ${getConnectionStatusColor()}`}>
                      {getConnectionStatusText()}
                    </span>
                  </div>
                </div>
                {lastConnected && connectionStatus === 'connected' && (
                  <div className="text-xs text-primary-300">
                    Connected since {new Date(lastConnected).toLocaleTimeString()}
                  </div>
                )}
                {connectNotice && (
                  <div className="mt-2 text-xs text-green-300 bg-green-500/10 rounded p-2" role="status">
                    {connectNotice}
                  </div>
                )}
                {shouldShowReconnect && (
                  <div className="mt-2 space-y-2">
                    {connectionStatus === 'error' && xmtpError && !installationRecovery && (
                      <div className="text-xs text-red-400 bg-red-500/10 rounded p-2">
                        {xmtpError}
                      </div>
                    )}
                    {connectionStatus === 'disconnected' && (
                      <div className="text-xs text-primary-300">
                        Not connected to the XMTP network. Messages won't sync until reconnected.
                      </div>
                    )}
                    {walletNeedsReconnect && (
                      <div className="text-xs text-yellow-400">
                        Wallet not connected. Please reconnect your wallet to sign in.
                      </div>
                    )}
                    {connectError && (
                      <div className="text-xs text-red-400 bg-red-500/10 rounded p-2">
                        {connectError}
                      </div>
                    )}
                    {installationRecovery && (
                      <div className="text-xs text-yellow-100 bg-yellow-500/10 border border-yellow-500/30 rounded p-3 space-y-2" role="alert">
                        <div className="font-semibold">Saved browser installation unavailable</div>
                        <p>
                          Converge found the correct inbox, but this browser's local XMTP
                          database {installationRecoveryView?.reason}.
                          {' '}Ledger changes happen only inside the confirmed Repair action;
                          Converge will not delete messages or reset this database.
                        </p>
                        <p className="text-yellow-200/80">
                          Inbox usage: {installationRecovery.existingInstallationCount}/10.
                          {' '}{installationRepairOutcome}
                        </p>
                        {canRepairInstallation && (
                          <button
                            onClick={() => {
                              void handleConnectionAction('repair');
                            }}
                            disabled={isReconnecting || !identity}
                            className="btn-primary text-xs disabled:opacity-50"
                          >
                            {activeConnectionAction === 'repair'
                              ? 'Repairing Browser…'
                              : 'Repair This Browser'}
                          </button>
                        )}
                      </div>
                    )}
                    <button
                      onClick={() => {
                        void handleConnectionAction('reconnect');
                      }}
                      disabled={isReconnecting || !identity || hasLiveRepairCandidate}
                      className="btn-primary text-xs disabled:opacity-50"
                    >
                      {activeConnectionAction === 'reconnect'
                        ? 'Checking Saved Installation…'
                        : installationRecovery
                          ? 'Check Saved Installation Again'
                          : connectionStatus === 'error'
                            ? 'Retry Connection'
                            : 'Connect'}
                    </button>
                    {hasLiveRepairCandidate && (
                      <div className="text-xs text-primary-300">
                        Finish or retry Repair This Browser before checking the saved installation again; this keeps the current repair key alive.
                      </div>
                    )}
                    {showConnectorList && (
                      <div className="space-y-2">
                        <div className="text-xs text-primary-300">Choose a wallet to reconnect:</div>
                        <div className="space-y-2">
                          {walletOptions.map((option) => (
                              <button
                                key={option.id}
                                onClick={async () => {
                                  try {
                                    setConnectError(null);
                                    const connected = await connectWallet(option);
                                    const connectedAddress = connected?.accounts?.[0];
                                    if (!connectedAddress || !connected?.signMessage) {
                                      throw new Error(
                                        'The wallet connected without an account-bound signer. Reconnect it and retry.'
                                      );
                                    }
                                    await handleConnectionAction(
                                      pendingWalletAction,
                                      {
                                        address: connectedAddress,
                                        chainId: connected.chainId,
                                        signMessage: connected.signMessage,
                                      },
                                      pendingWalletAction === 'repair'
                                    );
                                  } catch (err) {
                                    setConnectError(formatWalletConnectionError(err));
                                  }
                                }}
                                className="w-full p-4 bg-primary-950/60 hover:bg-primary-900 border border-primary-800/60 hover:border-accent-400 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-left"
                                disabled={isReconnecting || option.disabled}
                              >
                                <div className="flex items-center gap-3">
                                  <span className="text-3xl">{option.icon}</span>
                                  <div>
                                    <div className="text-sm font-medium text-primary-50">{option.name}</div>
                                    {option.description && (
                                      <div className="text-xs text-primary-300">{option.description}</div>
                                    )}
                                  </div>
                                </div>
                              </button>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
                {connectionStatus === 'connecting' && (
                  <div className="mt-2 text-xs text-primary-200">
                    <div className="flex items-center gap-2">
                      <svg className="animate-spin h-3 w-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                      </svg>
                      <span>
                        Reopening and verifying this browser's saved installation…
                      </span>
                    </div>
                    <div className="mt-1 text-primary-300">
                      No new installation is created during an ordinary reconnect. Advanced troubleshooting has more detail.
                    </div>
                  </div>
                )}
              </div>

              {/* Current Identity */}
              <div className="p-4">
                <div className="flex items-center justify-between mb-1">
                  <div className="font-medium">Current Identity</div>
                  <button
                    onClick={() => setShowQR(true)}
                    className="flex items-center gap-1 text-sm text-accent-300 hover:text-accent-200 transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
                    </svg>
                    Show QR Code
                  </button>
                </div>
                <div className="text-sm text-primary-200 mb-2">Ethereum Address</div>
                <div className="font-mono text-sm bg-primary-950/20 rounded px-3 py-2 break-all">
                  {identity?.address}
                </div>
                <div className="mt-2 text-xs text-primary-300">
                  {identity?.privateKey
                    ? 'This local account key signs Converge messages. Export is available under Advanced.'
                    : 'This external wallet is the account identity for this XMTP inbox.'}
                </div>
              </div>

            </div>
          </section>

          {/* Inbox Actions */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Inbox</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <button
                onClick={handleBurnInbox}
                disabled={isBurningInbox || !identity?.inboxId}
                className="w-full p-4 text-left hover:bg-primary-950/60 transition-colors flex items-center justify-between text-red-400 disabled:opacity-50"
              >
                <div>
                  <div className="font-medium">{isBurningInbox ? 'Burning Inbox...' : 'Burn Inbox'}</div>
                  <div className="text-sm text-primary-200">Revoke this installation when possible, then wipe this inbox from the browser</div>
                </div>
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
                  />
                </svg>
              </button>
            </div>
          </section>

          {/* Privacy & Security */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Privacy & Security</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Message Encryption</div>
                    <div className="text-sm text-primary-200">End-to-end encryption via XMTP</div>
                  </div>
                  <span className="text-sm text-green-500">✓ Enabled</span>
                </div>
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Local Storage</div>
                    <div className="text-sm text-primary-200">Private keys, recovery phrases, and decrypted app data are stored unencrypted in this browser</div>
                  </div>
                  <span className="text-sm text-amber-300">Local only</span>
                </div>
              </div>
              <div className="p-4">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <div className="font-medium">Message Retention</div>
                    <div className="text-sm text-primary-200">
                      New chats request a two-week XMTP disappearing-message period. Existing chats keep their shared setting. The browser's older 28-day local-history cutoff remains unchanged.
                    </div>
                  </div>
                  <span className="whitespace-nowrap text-sm text-green-500">14-day default</span>
                </div>
              </div>
            </div>
          </section>

          {/* Data Management */}
          <section>
            <h2 className="text-lg font-semibold mb-3">Data Management</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <div className="font-medium">Storage Usage</div>
                    <div className="text-sm text-primary-200">Local database size</div>
                  </div>
                  {storageSize !== null && (
                    <span className="text-sm text-primary-100">{formatBytes(storageSize)}</span>
                  )}
                </div>
                <button
                  onClick={loadStorageSize}
                  disabled={isLoadingSize}
                  className="text-sm text-accent-300 hover:text-accent-200"
                >
                  {isLoadingSize ? 'Calculating...' : 'Calculate Size'}
                </button>
              </div>

            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Advanced</h2>
            <details className="bg-primary-900/60 border border-primary-800/60 rounded-lg backdrop-blur">
              <summary className="cursor-pointer p-4 font-medium text-primary-100">
                Recovery & troubleshooting
              </summary>
              <div className="border-t border-primary-800/60 divide-y divide-primary-800/60">
                <button
                  onClick={handleDownloadKeyfile}
                  disabled={!canDownloadKeyfile}
                  className="w-full p-4 text-left flex items-center justify-between transition-colors hover:bg-primary-950/60 disabled:cursor-not-allowed disabled:text-primary-400"
                >
                  <div>
                    <div className="font-medium">Download keyfile</div>
                    <div className="text-sm text-primary-200">
                      {canDownloadKeyfile
                        ? 'Exports the unencrypted local account key'
                        : 'No exportable local account key is available'}
                    </div>
                  </div>
                  <svg className="w-5 h-5 text-primary-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5m0 0l5-5m-5 5V4" />
                  </svg>
                </button>
                <button
                  onClick={handleClearData}
                  className="w-full p-4 text-left hover:bg-primary-950/60 transition-colors flex items-center justify-between text-red-400"
                >
                  <div>
                    <div className="font-medium">Clear All Browser Data</div>
                    <div className="text-sm text-primary-200">Remove every Converge inbox and local database without remote revocation</div>
                  </div>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                </button>
                <button
                  onClick={() => navigate('/debug')}
                  className="w-full p-4 text-left hover:bg-primary-950/60 transition-colors flex items-center justify-between"
                >
                  <div>
                    <div className="font-medium">Troubleshooting</div>
                    <div className="text-sm text-primary-200">Connection diagnostics and manual recovery tools</div>
                  </div>
                  <span className="text-primary-300" aria-hidden>›</span>
                </button>
              </div>
            </details>
          </section>

          {/* App */}
          <section>
            <h2 className="text-lg font-semibold mb-3">App</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Notifications</div>
                    <div className="text-sm text-primary-200">{pushDescription}</div>
                  </div>
                  {pushStatus !== 'unsupported' && (
                    <button
                      type="button"
                      role="switch"
                      aria-checked={pushIsOn}
                      aria-label={pushIsOn ? 'Disable notifications' : 'Enable notifications'}
                      onClick={pushIsOn ? handleDisablePush : handleEnablePush}
                      disabled={
                        isPushLoading ||
                        pushStatus === 'unknown' ||
                        (!pushIsOn && pushPreparation === 'preparing')
                      }
                      className={`relative h-6 w-11 flex-shrink-0 rounded-full transition-colors disabled:opacity-50 ${
                        pushIsOn ? 'bg-accent-500' : 'bg-primary-700'
                      }`}
                    >
                      <span
                        className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-transform ${
                          pushIsOn ? 'translate-x-5' : 'translate-x-0.5'
                        }`}
                      />
                    </button>
                  )}
                </div>
                {pushFeedback && (
                  <div
                    role={pushFeedback.tone === 'error' ? 'alert' : 'status'}
                    className={`mt-3 text-sm ${
                      pushFeedback.tone === 'error'
                        ? 'text-red-300'
                        : pushFeedback.tone === 'success'
                          ? 'text-green-300'
                          : 'text-primary-200'
                    }`}
                  >
                    {pushFeedback.message}
                  </div>
                )}
              </div>
            </div>
          </section>

          <details className="bg-primary-900/60 border border-primary-800/60 rounded-lg backdrop-blur">
            <summary className="cursor-pointer p-4 font-medium text-primary-100">
              Devices & recovery
            </summary>
            <div className="border-t border-primary-800/60 p-4">
              <InstallationsSettings />
            </div>
          </details>

          {/* About */}
          <section>
            <h2 className="text-lg font-semibold mb-3">About</h2>
            <div className="bg-primary-900/60 border border-primary-800/60 rounded-lg divide-y divide-primary-800/60 backdrop-blur">
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <span className="text-primary-200">Version</span>
                  <span>{buildInfo.version}</span>
                </div>
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <span className="text-primary-200">Protocol</span>
                  <span>XMTP protocol v3 (SDK v6.1.2)</span>
                </div>
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between">
                  <span className="text-primary-200">Storage</span>
                  <span>IndexedDB (Dexie)</span>
                </div>
              </div>
              <div className="p-4">
                <a
                  href="https://github.com/pierce403/converge.cv"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-between text-accent-300 hover:text-accent-200"
                >
                  <span>View on GitHub</span>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                </a>
              </div>
            </div>
          </section>

          {/* Footer info */}
          <div className="text-center text-sm text-primary-300 pb-8">
            <p>Converge - Local-first XMTP messaging</p>
            <p className="mt-1">End-to-end encrypted · No server storage</p>
          </div>
        </div>
      </div>

      {/* QR Code Overlay */}
      {showQR && identity && (
        <QRCodeOverlay address={identity.address} onClose={() => setShowQR(false)} />
      )}

    </div>
  );
}
