/**
 * Authentication hook
 */

import { useCallback } from 'react';
import {
  INBOX_ALREADY_LOADED_MESSAGE,
  useAuthStore,
  useInboxRegistryStore,
} from '@/lib/stores';
import { getStorage, getStorageNamespace, setStorageNamespace } from '@/lib/storage';
import { ensureInboxStorageNamespace } from '@/lib/storage/namespacing';
import { useXmtpStore } from '@/lib/stores/xmtp-store';
import { lockVault } from '@/lib/crypto';
import { getXmtpClient } from '@/lib/xmtp';
import type { ConnectResult, RepairInstallationResult } from '@/lib/xmtp/client';
import {
  expectedInstallationForStoredIdentity,
  registrationPolicyForStoredIdentity,
  type ClientRegistrationPolicy,
} from '@/lib/xmtp/registration-policy';
import { privateKeyToAccount } from 'viem/accounts';
import type { Identity } from '@/types';
import { useWalletConnection } from '@/lib/wagmi';
import { clearLastRoute } from '@/lib/utils/route-persistence';
import { inboxIdsMatch, normalizeInboxId } from '@/lib/utils/inbox';
import {
  extractWrongChainIdDetails,
  isLegacyScwChainZeroMismatch,
  legacyScwChainZeroRecoveryMessage,
} from '@/lib/xmtp/installation-recovery';
import {
  completeProvisioning,
  getScwRetryChainId,
  recordInstallationReady,
} from '@/lib/xmtp/device-provisioning';
import { loadStoredIdentityForXmtp } from './xmtp-storage';
import { findPendingKeyfileRestore } from './keyfile-resume';
import { planPendingNewInboxAttempts } from './new-inbox-resume';
import {
  isAutoGeneratedDisplayName,
  isUsableNetworkDisplayName,
} from '@/lib/identity/profile-suggestions';
import { installationIdsMatch } from '@/lib/xmtp/client-registration';
import { selectPreviousInstallationForRepair } from '@/lib/xmtp/installation-repair';
import {
  clearIntentionalEmptyInboxState,
} from './onboarding-state';
import { burnInbox } from '@/lib/identity/burn-inbox';
import { isInboxLoadedLocally } from '@/lib/identity/loaded-inbox';
import {
  ethereumAddressesEqual,
  requireEthereumAddress,
} from '@/lib/utils/ethereum';
import { getMessageRetentionCutoff } from '@/lib/message-retention-policy';
import {
  isLegacyDeviceJoinIdentity,
  migrateLegacyDeviceJoinIdentity,
} from '@/lib/identity/migration';

export function useAuth() {
  const authStore = useAuthStore();
  const { setIdentity, setVaultSecrets, setAuthenticated, setVaultUnlocked } = authStore;
  const isE2E = import.meta.env.VITE_E2E_TEST === 'true';
  const { address: walletAddress, chainId: walletChainId, signMessage: walletSignMessage } = useWalletConnection();

  const connectXmtpSafely = useCallback(
    async (
      address: string,
      privateKey?: string,
      chainId?: number,
      signMessage?: (message: string) => Promise<string>,
      options?: {
        registrationPolicy?: ClientRegistrationPolicy;
        enableHistorySync?: boolean;
        labelOverride?: string;
        skipRegistryUpdate?: boolean;
        required?: boolean;
        expectedInboxId?: string;
        expectedInstallationId?: string;
        requestHistorySync?: boolean;
        walletType?: 'EOA' | 'SCW';
      }
    ): Promise<ConnectResult | null> => {
      try {
        const canonicalAddress = requireEthereumAddress(address, 'XMTP identity address');
        if (isE2E) {
          // Skip live XMTP connection during E2E.
          const storage = await getStorage();
          const identity = await storage.getIdentityByAddress(canonicalAddress);
          if (identity && ethereumAddressesEqual(identity.address, canonicalAddress)) {
            const stubInboxId = identity.inboxId || `local-${canonicalAddress.slice(2, 10)}`;
            const stubInstallationId =
              identity.installationId || `local-installation-${canonicalAddress.slice(2, 10)}`;
            identity.inboxId = stubInboxId;
            identity.installationId = stubInstallationId;
            identity.provisioningPending = false;
            await storage.putIdentity(identity);
            setIdentity(identity);

            if (!options?.skipRegistryUpdate) {
              const registry = useInboxRegistryStore.getState();
              const label =
                options?.labelOverride ||
                identity.displayName ||
                `${identity.address.slice(0, 6)}…${identity.address.slice(-4)}`;

              registry.upsertEntry({
                inboxId: stubInboxId,
                displayLabel: label,
                avatar: identity.avatar,
                primaryDisplayIdentity: identity.displayName || identity.address,
                lastOpenedAt: Date.now(),
                hasLocalDB: true,
              });
              registry.markOpened(stubInboxId, true);
            }

            await ensureInboxStorageNamespace(stubInboxId, identity);
            return {
              inboxId: stubInboxId,
              installationId: stubInstallationId,
              installationRegistered: true,
              historySyncRequested: false,
              historySyncRequired: false,
            };
          }
          return null;
        }

      const xmtp = getXmtpClient();
      const shouldSyncHistory =
        options?.enableHistorySync !== undefined ? options.enableHistorySync : false;

      // Pull the persisted identity so the XMTP client can throttle redundant syncs across reloads.
      let lastSyncedAt: number | undefined;
      const storedIdentity = await loadStoredIdentityForXmtp(canonicalAddress);
      if (storedIdentity && typeof storedIdentity.lastSyncedAt === 'number') {
        lastSyncedAt = storedIdentity.lastSyncedAt;
      }

      if (options?.requestHistorySync && storedIdentity && !storedIdentity.needsHistorySync) {
        storedIdentity.needsHistorySync = true;
        const storage = await getStorage();
        await storage.putIdentity(storedIdentity);
        setIdentity(storedIdentity);
      }

      const result = await xmtp.connect(
        {
          address: canonicalAddress,
          privateKey,
          chainId,
          walletType: options?.walletType ?? storedIdentity?.walletType,
          signMessage,
          displayName: options?.labelOverride,
          lastSyncedAt,
          inboxId: storedIdentity?.inboxId,
          installationId: storedIdentity?.installationId,
          xmtpDbPathMode: storedIdentity?.xmtpDbPathMode,
        },
        {
          registrationPolicy: options?.registrationPolicy ?? 'resume-only',
          enableHistorySync: shouldSyncHistory,
          expectedInboxId: options?.expectedInboxId,
          expectedInstallationId: options?.expectedInstallationId,
          requestHistorySync: options?.requestHistorySync,
          onInstallationReady: async (ready) => {
            const storage = await getStorage();
            const identity = await storage.getIdentityByAddress(canonicalAddress);
            if (!identity) {
              return;
            }
            const updated = recordInstallationReady(identity, ready);
            await storage.putIdentity(updated);
            setIdentity(updated);
            await ensureInboxStorageNamespace(updated.inboxId, updated);
          },
        }
      );

        const inboxIdRaw = xmtp.getInboxId();
        const inboxId = normalizeInboxId(inboxIdRaw);
        const installationId = xmtp.getInstallationId();

        if (inboxId && installationId) {
          const storage = await getStorage();
          const identity = await storage.getIdentityByAddress(canonicalAddress);
          if (identity && ethereumAddressesEqual(identity.address, canonicalAddress)) {
            let completedIdentity = completeProvisioning(
              {
                ...identity,
                needsHistorySync:
                  identity.needsHistorySync ||
                  (result.historySyncRequired && !result.historySyncRequested),
              },
              result
            );
            if (
              completedIdentity.installationRepairPending &&
              installationIdsMatch(completedIdentity.installationId, result.installationId)
            ) {
              completedIdentity = {
                ...completedIdentity,
                installationRepairPending: false,
              };
            }
            await storage.putIdentity(completedIdentity);

            setIdentity(completedIdentity);

            if (!options?.skipRegistryUpdate) {
              const registry = useInboxRegistryStore.getState();
              const label =
                options?.labelOverride ||
                completedIdentity.displayName ||
                `${completedIdentity.address.slice(0, 6)}…${completedIdentity.address.slice(-4)}`;

              registry.upsertEntry({
                inboxId,
                displayLabel: label,
                avatar: completedIdentity.avatar,
                primaryDisplayIdentity: completedIdentity.displayName || completedIdentity.address,
                lastOpenedAt: Date.now(),
                hasLocalDB: true,
              });
              registry.markOpened(inboxId, true);
            }

            await ensureInboxStorageNamespace(inboxId, completedIdentity);

            console.log('[Auth] Saved XMTP info to identity:', {
              inboxId,
              installationId: installationId.substring(0, 16) + '...',
            });

            // Try to load profile (display name/avatar) from network and persist locally
            try {
              const profile = await xmtp.loadOwnProfile();
              if (profile && (profile.displayName || profile.avatarUrl)) {
                const updated = { ...completedIdentity } as Identity;
                if (
                  profile.displayName &&
                  isAutoGeneratedDisplayName(completedIdentity.displayName) &&
                  isUsableNetworkDisplayName(profile.displayName, completedIdentity)
                ) {
                  updated.displayName = profile.displayName.trim();
                }
                if (profile.avatarUrl) (updated as Identity & { avatar?: string }).avatar = profile.avatarUrl;
                await storage.putIdentity(updated);
                setIdentity(updated);
                console.log('[Auth] Applied profile from network');
              }
            } catch (e) {
              console.warn('[Auth] Failed to load profile from network (non-fatal):', e);
            }
          }
        }
        return result;
      } catch (error) {
        if (options?.required) {
          throw error;
        }
        console.warn('XMTP connection failed (non-blocking):', error);
        return null;
      }
    },
    [setIdentity, isE2E]
  );

  /**
   * Create a new identity without passphrase (simplified flow)
   */
  const createIdentity = useCallback(
    async (
      walletAddress: string,
      privateKey?: string,
      chainId?: number,
      signMessage?: (message: string) => Promise<string>,
      options?: {
        registrationPolicy?: ClientRegistrationPolicy;
        enableHistorySync?: boolean;
        label?: string;
        skipRegistryUpdate?: boolean;
        mnemonic?: string;
        identityKind?: Identity['identityKind'];
        linkedWalletAddress?: string;
        linkedWalletChainId?: number;
        linkedAt?: number;
        previousInboxId?: string;
        provisioningMode?: Identity['provisioningMode'];
        xmtpDbPathMode?: Identity['xmtpDbPathMode'];
        expectedInboxId?: string;
        expectedInstallationId?: string;
        requestHistorySync?: boolean;
        deferAuthentication?: boolean;
      }
    ) => {
      const previousSession = useAuthStore.getState();
      const previousNamespace = getStorageNamespace();
      let attemptedAddress = walletAddress;
      try {
        const storage = await getStorage();

        let pendingIdentity: Identity | undefined;
        if (
          options?.provisioningMode === 'new-inbox' ||
          options?.provisioningMode === 'keyfile-restore'
        ) {
          const identities = await storage.listIdentities();
          if (options.provisioningMode === 'new-inbox') {
            const pendingPlan = planPendingNewInboxAttempts(identities, {
              // A user who is already inside an inbox is asking for another
              // independent inbox. Never let a stale flag on the loaded signer
              // replace the freshly generated key for that explicit action.
              excludeAddress: previousSession.isAuthenticated
                ? previousSession.identity?.address
                : undefined,
            });
            pendingIdentity = pendingPlan.resumable;
            for (const discardable of pendingPlan.discardable) {
              await storage.deleteIdentityByAddress(discardable.address);
            }
            if (pendingPlan.discardable.length > 0) {
              console.info(
                `[Auth] Removed ${pendingPlan.discardable.length} incomplete pre-registration inbox attempt(s).`
              );
            }
          } else {
            pendingIdentity = findPendingKeyfileRestore(identities, {
                address: walletAddress,
                privateKey,
                inboxId: options.expectedInboxId,
              });
          }
        }

        const effectiveAddress = requireEthereumAddress(
          pendingIdentity?.address ?? walletAddress,
          'XMTP identity address'
        );
        const effectivePrivateKey = pendingIdentity?.privateKey ?? privateKey;
        const effectiveMnemonic = pendingIdentity?.mnemonic ?? options?.mnemonic;

        let publicKeyHex = '';
        
        // Only derive public key if we have a valid private key (generated wallets)
        // For connected wallets, we don't have the private key (wallet keeps it secure)
        if (effectivePrivateKey && effectivePrivateKey !== '0x0000000000000000000000000000000000000000000000000000000000000000') {
          const account = privateKeyToAccount(effectivePrivateKey as `0x${string}`);
          publicKeyHex = account.publicKey;
        }
        
        // Create identity
        const identity: Identity = {
          ...pendingIdentity,
          address: effectiveAddress,
          publicKey: publicKeyHex,
          privateKey: effectivePrivateKey, // Stored as plaintext in browser IndexedDB today.
          createdAt: pendingIdentity?.createdAt ?? Date.now(),
          displayName: pendingIdentity?.displayName ?? options?.label,
          identityKind: pendingIdentity?.identityKind ?? options?.identityKind,
          walletType: effectivePrivateKey ? 'EOA' : undefined,
          walletChainId: effectivePrivateKey ? undefined : chainId,
          linkedWalletAddress: options?.linkedWalletAddress,
          linkedWalletChainId: options?.linkedWalletChainId,
          linkedAt: options?.linkedAt,
          previousInboxId: options?.previousInboxId,
          provisioningMode: options?.provisioningMode,
          provisioningPending: true,
          xmtpDbPathMode: options?.xmtpDbPathMode ?? 'inbox-default',
          expectedInboxId: pendingIdentity?.expectedInboxId ?? options?.expectedInboxId,
          installationId: pendingIdentity?.installationId,
          inboxId: pendingIdentity?.inboxId,
          needsHistorySync:
            pendingIdentity?.needsHistorySync ?? options?.requestHistorySync ?? false,
        };
        attemptedAddress = identity.address;
        if (effectiveMnemonic) {
          identity.mnemonic = effectiveMnemonic;
        }
        await storage.putIdentity(identity);

        // Keep the key available while XMTP provisions, but do not mark onboarding
        // complete until the live inbox and installation have been verified.
        setIdentity(identity);

        // Connect XMTP with appropriate signer
        const connection = await connectXmtpSafely(
          identity.address,
          effectivePrivateKey && effectivePrivateKey !== '0x0000000000000000000000000000000000000000000000000000000000000000' ? effectivePrivateKey : undefined,
          chainId,
          signMessage,
          {
            registrationPolicy: options?.registrationPolicy ?? 'resume-only',
            enableHistorySync:
              options?.enableHistorySync !== undefined ? options.enableHistorySync : false,
            labelOverride: options?.label,
            skipRegistryUpdate: options?.skipRegistryUpdate,
            required: true,
            expectedInboxId: identity.expectedInboxId,
            expectedInstallationId:
              options?.expectedInstallationId ??
              (identity.provisioningPending ? identity.installationId : undefined),
            requestHistorySync: options?.requestHistorySync || identity.needsHistorySync,
          }
        );

        if (!connection) {
          throw new Error('XMTP did not return a verified inbox installation.');
        }

        clearIntentionalEmptyInboxState();
        if (!options?.deferAuthentication) {
          setAuthenticated(true);
          setVaultUnlocked(true);
        }

        return true;
      } catch (error) {
        console.error('Failed to create identity:', error);
        if (error instanceof Error) {
          console.error('Error message:', error.message);
          console.error('Error stack:', error.stack);
        }
        if (
          previousSession.isAuthenticated &&
          previousSession.identity &&
          !ethereumAddressesEqual(previousSession.identity.address, attemptedAddress)
        ) {
          try {
            await setStorageNamespace(previousNamespace);
            setIdentity(previousSession.identity);
            setAuthenticated(true);
            setVaultUnlocked(previousSession.isVaultUnlocked);
            if (previousSession.identity.privateKey) {
              await connectXmtpSafely(
                previousSession.identity.address,
                previousSession.identity.privateKey,
                undefined,
                undefined,
                {
                  registrationPolicy: 'resume-only',
                  enableHistorySync: false,
                  labelOverride: previousSession.identity.displayName,
                  skipRegistryUpdate: true,
                  expectedInboxId:
                    previousSession.identity.expectedInboxId ?? previousSession.identity.inboxId,
                  expectedInstallationId:
                    expectedInstallationForStoredIdentity(previousSession.identity),
                }
              );
            }
          } catch (restoreError) {
            console.warn('[Auth] Failed to restore the previous session after provisioning:', restoreError);
          }
        }
        throw error;
      }
    },
    [setIdentity, setAuthenticated, setVaultUnlocked, connectXmtpSafely]
  );


  /**
   * Logout completely
   */
  const logout = useCallback(async () => {
    console.log('[Auth] Logging out - clearing all data...');

    try {
      const xmtp = getXmtpClient();
      await xmtp.disconnect();
    } catch (error) {
      console.warn('[Auth] Failed to disconnect XMTP (non-fatal):', error);
    }

    try {
      const storage = await getStorage();
      await storage.clearAllData();
      await storage.deleteIdentity();
      await storage.deleteVaultSecrets();
    } catch (error) {
      console.warn('[Auth] Failed to clear local storage (non-fatal):', error);
    }

    try {
      await setStorageNamespace('default');
    } catch (error) {
      console.warn('[Auth] Failed to reset storage namespace (non-fatal):', error);
    }

    try {
      lockVault();
    } catch (error) {
      console.warn('[Auth] Failed to lock vault (non-fatal):', error);
    }

    try {
      clearLastRoute();
    } catch (error) {
      console.warn('[Auth] Failed to clear last route (non-fatal):', error);
    }

    try {
      authStore.logout();
    } catch (error) {
      console.warn('[Auth] Failed to clear auth store (non-fatal):', error);
    }

    try {
      useInboxRegistryStore.getState().reset();
    } catch (error) {
      console.warn('[Auth] Failed to reset inbox registry (non-fatal):', error);
    }

    clearIntentionalEmptyInboxState();

    console.log('[Auth] ✅ Logout complete - all data cleared');
  }, [authStore]);

  const burnIdentity = useCallback(async (inboxId: string) => burnInbox(inboxId), []);

  /**
   * Check if user has existing identity
   */
  const checkExistingIdentity = useCallback(async (): Promise<boolean> => {
    try {
      const registry = useInboxRegistryStore.getState();
      registry.hydrate();

      // If an explicit inbox was selected just before reload, honor it
      try {
        const forced = typeof window !== 'undefined' ? window.localStorage.getItem('converge.forceInboxId.v1') : null;
        if (forced && forced.trim().length > 0) {
          const normalizedForced = normalizeInboxId(forced);
          registry.setCurrentInbox(normalizedForced);
          // Persist storage namespace early so the next getStorage() uses the right shard
          if (normalizedForced) {
            await setStorageNamespace(normalizedForced);
          }
          // Clear the one-shot hint
          window.localStorage.removeItem('converge.forceInboxId.v1');
        }
      } catch (e) {
        // non-fatal
      }

      // Ensure storage namespace is aligned with the current registry inbox before instantiating storage
      // setCurrentInbox() replaces the Zustand state object; reacquire it after
      // consuming the one-shot switch hint instead of reading the stale snapshot.
      const normalizedRegistryInbox = normalizeInboxId(
        useInboxRegistryStore.getState().currentInboxId
      );
      if (normalizedRegistryInbox) {
        try {
          await setStorageNamespace(normalizedRegistryInbox);
        } catch {
          // ignore
        }
      }

      const ensureNamespaceAndReload = async (inboxId: string) => {
        const normalizedInboxId = normalizeInboxId(inboxId);
        if (!normalizedInboxId) {
          throw new Error('Invalid inbox id for namespace reload');
        }

        await setStorageNamespace(normalizedInboxId);
        const targetStorage = await getStorage();
        const identitiesForInbox = await targetStorage.listIdentities();
        return { storage: targetStorage, identities: identitiesForInbox };
      };

      let storage = await getStorage();
      let identities = await storage.listIdentities();
      if (!identities.length) {
        try {
          await setStorageNamespace('default');
        } catch {
          // ignore; storage may already be on the default namespace
        }

        // Onboarding owns identity creation. In particular, a user choosing to
        // join an existing inbox must not get a standalone inbox first.
        return false;
      }

      let identity: Identity | undefined;

      if (normalizedRegistryInbox) {
        identity = identities.find((item) => inboxIdsMatch(item.inboxId, normalizedRegistryInbox));

        // If we have a registry-selected inbox but the current namespace doesn't contain it,
        // switch namespaces to that inbox and reload identities from that shard.
        if (!identity) {
          try {
            const result = await ensureNamespaceAndReload(normalizedRegistryInbox);
            storage = result.storage;
            identities = result.identities;
            identity = identities.find((item) => inboxIdsMatch(item.inboxId, normalizedRegistryInbox));
          } catch (error) {
            console.warn('[Auth] Failed to switch storage namespace for registry inbox:', error);
          }
        }
      }

      // If no identity is selected yet, iterate through registry entries to locate the correct namespace
      if (!identity && registry.entries.length > 0) {
        for (const entry of registry.entries) {
          try {
            const result = await ensureNamespaceAndReload(entry.inboxId);
            storage = result.storage;
            identities = result.identities;
            identity = identities.find((item) => inboxIdsMatch(item.inboxId, entry.inboxId));
            if (identity) {
              registry.setCurrentInbox(entry.inboxId);
              break;
            }
          } catch (error) {
            console.warn('[Auth] Failed to switch storage namespace while searching registry entries:', error);
          }
        }
      }

      // If a preferred inbox was selected (e.g., via the inbox switcher) but no identity
      // was found in that namespace, avoid falling back to a different inbox. Continuing
      // with another identity causes the UI to show the wrong avatar/name after the
      // hard reload triggered by the switcher.
      if (!identity && normalizedRegistryInbox) {
        console.warn('[Auth] Current inbox selected but no identity found for it; aborting auto-login');
        return false;
      }

      if (!identity) {
        // Fallback: pick the most recently opened from the registry list or the first identity in this namespace
        const currentId = registry.currentInboxId;
        if (currentId) {
          identity = identities.find((it) => inboxIdsMatch(it.inboxId, currentId)) || identities[0];
        } else {
          identity = identities[0];
        }
      }

      if (!identity) {
        return false;
      }

      const normalizedIdentityInboxId = normalizeInboxId(identity.inboxId);
      if (normalizedIdentityInboxId && identity.inboxId !== normalizedIdentityInboxId) {
        identity = { ...identity, inboxId: normalizedIdentityInboxId } as Identity;
      }

      // Repair message previews and attachment rows before authenticated UI can
      // render stale content from the selected inbox.
      await storage.pruneMessages(getMessageRetentionCutoff());
      const secrets = await storage.getVaultSecrets();

      // Check if this identity requires migration to direct external wallet model
      if (isLegacyDeviceJoinIdentity(identity)) {
        console.info(
          '[Auth] Legacy device-join identity detected; migration to direct external wallet required.'
        );
        identity = {
          ...identity,
          migrationRequired: true,
          migrationTargetWallet: identity.linkedWalletAddress,
          migrationOldLocalAddress: identity.address,
        };
        setIdentity(identity);
        setVaultSecrets(secrets ?? null);
        setAuthenticated(false);
        setVaultUnlocked(false);
        return false;
      }

      setIdentity(identity);
      setVaultSecrets(secrets ?? null);
      const isPendingProvisioning = identity.provisioningPending === true || !identity.inboxId;
      if (!isPendingProvisioning) {
        setAuthenticated(true);
        setVaultUnlocked(true);
        clearIntentionalEmptyInboxState();
      }

      if (typeof identity.lastSyncedAt === 'number') {
        useXmtpStore.getState().setLastSyncedAt(identity.lastSyncedAt);
      }

      const registryEntry = identity.inboxId
        ? registry.entries.find((entry) => inboxIdsMatch(entry.inboxId, identity!.inboxId))
        : undefined;
      const shouldSyncHistory = registryEntry ? !registryEntry.hasLocalDB : true;
      const shouldRequestDeviceHistory = Boolean(
        identity.needsHistorySync ||
          (shouldSyncHistory && identity.provisioningMode !== 'new-inbox')
      );

      if (identity.privateKey) {
        const connection = await connectXmtpSafely(identity.address, identity.privateKey, undefined, undefined, {
          registrationPolicy: registrationPolicyForStoredIdentity(
            identity,
            isPendingProvisioning
          ),
          enableHistorySync: shouldSyncHistory,
          requestHistorySync: shouldRequestDeviceHistory,
          labelOverride: identity.displayName,
          required: isPendingProvisioning,
          expectedInboxId: identity.expectedInboxId ?? identity.inboxId,
          expectedInstallationId: expectedInstallationForStoredIdentity(identity),
        });
        if (isPendingProvisioning && connection) {
          clearIntentionalEmptyInboxState();
          setAuthenticated(true);
          setVaultUnlocked(true);
        }
      } else {
        // Direct external-wallet identity: connect signer-less (or with signer if wallet currently connected)
        console.log('[Auth] Connecting external-wallet identity (signer-less routine startup)');
        const signMessage =
          walletAddress && ethereumAddressesEqual(walletAddress, identity.address) && walletSignMessage
            ? async (message: string) => {
                return await walletSignMessage(message, identity.address);
              }
            : undefined;

        const connection = await connectXmtpSafely(
          identity.address,
          undefined,
          walletChainId ?? identity.walletChainId,
          signMessage,
          {
            registrationPolicy: 'resume-only',
            enableHistorySync: shouldSyncHistory,
            requestHistorySync: shouldRequestDeviceHistory,
            walletType: identity.walletType,
            labelOverride: identity.displayName,
            required: isPendingProvisioning,
            expectedInboxId: identity.expectedInboxId ?? identity.inboxId,
            expectedInstallationId: expectedInstallationForStoredIdentity(identity),
          }
        );
        if (isPendingProvisioning && connection) {
          clearIntentionalEmptyInboxState();
          setAuthenticated(true);
          setVaultUnlocked(true);
        }
      }

      if (identity.inboxId) {
        registry.markOpened(identity.inboxId, registryEntry?.hasLocalDB ?? true);
      }

      return true;
    } catch (error) {
      console.error('Failed to check existing identity:', error);
      return false;
    }
  }, [
    setIdentity,
    setVaultSecrets,
    setAuthenticated,
    setVaultUnlocked,
    connectXmtpSafely,
    walletAddress,
    walletChainId,
    walletSignMessage,
  ]);

  const probeIdentity = useCallback(
    async (
      walletAddress: string,
      privateKey?: string,
      chainId?: number,
      signMessage?: (message: string) => Promise<string>,
      walletType?: 'EOA' | 'SCW'
    ) => {
      const xmtp = getXmtpClient();
      return await xmtp.probeIdentity({
        address: walletAddress,
        privateKey,
        chainId,
        signMessage,
        walletType,
      });
    },
    []
  );

  const reconnectCurrentIdentity = useCallback(
    async (options?: {
      chainId?: number;
      signMessage?: (message: string) => Promise<string>;
      walletType?: 'EOA' | 'SCW';
    }): Promise<ConnectResult> => {
      const identity = useAuthStore.getState().identity;
      if (!identity) {
        throw new Error('No identity is currently loaded.');
      }

      const result = await connectXmtpSafely(
        identity.address,
        identity.privateKey,
        options?.chainId,
        options?.signMessage,
        {
          registrationPolicy: 'resume-only',
          enableHistorySync: false,
          labelOverride: identity.displayName,
          required: true,
          requestHistorySync: identity.needsHistorySync,
          walletType: options?.walletType ?? identity.walletType,
          expectedInboxId: identity.expectedInboxId ?? identity.inboxId,
          expectedInstallationId: expectedInstallationForStoredIdentity(identity),
        }
      );

      if (!result) {
        throw new Error('XMTP did not reconnect the current identity.');
      }
      return result;
    },
    [connectXmtpSafely]
  );

  const repairCurrentInstallation = useCallback(
    async (options?: {
      chainId?: number;
      signMessage?: (message: string) => Promise<string>;
      walletType?: 'EOA' | 'SCW';
    }): Promise<RepairInstallationResult> => {
      const identity = useAuthStore.getState().identity;
      const recovery = useXmtpStore.getState().installationRecovery;
      if (!identity) {
        throw new Error('No identity is currently loaded.');
      }
      if (!recovery) {
        throw new Error('Retry the saved installation first so Converge can inspect it safely.');
      }
      if (!identity.privateKey && !options?.signMessage) {
        throw new Error('Connect the wallet that controls this identity before repairing it.');
      }

      const xmtp = getXmtpClient();
      const result = await xmtp.repairInstallation(
        {
          address: identity.address,
          privateKey: identity.privateKey,
          chainId: options?.chainId ?? identity.walletChainId,
          walletType: options?.walletType ?? identity.walletType,
          signMessage: options?.signMessage,
          displayName: identity.displayName,
          inboxId: identity.inboxId,
          installationId: identity.installationId,
          xmtpDbPathMode: identity.xmtpDbPathMode,
        },
        {
          recovery,
          interruptedRepairCandidateId: identity.installationRepairPending
            ? identity.installationId
            : undefined,
          previousInstallationId: selectPreviousInstallationForRepair(identity, recovery),
          expectedInboxId: identity.expectedInboxId ?? identity.inboxId,
          enableHistorySync: false,
          requestHistorySync: true,
          onCandidateReady: async (candidate) => {
            const storage = await getStorage();
            const current = await storage.getIdentityByAddress(identity.address);
            if (!current) {
              throw new Error('The selected identity changed while browser repair was preparing.');
            }
            const currentInboxId = current.expectedInboxId ?? current.inboxId;
            if (!currentInboxId || !inboxIdsMatch(currentInboxId, candidate.inboxId)) {
              throw new Error(
                'The selected inbox changed while browser repair was preparing. No registration was attempted.'
              );
            }
            if (
              (current.installationId || identity.installationId) &&
              !installationIdsMatch(current.installationId, identity.installationId)
            ) {
              throw new Error(
                'Another Converge tab updated this browser installation or repair journal. No registration was attempted; reload before retrying.'
              );
            }
            const previousInstallationId = selectPreviousInstallationForRepair(
              current,
              recovery
            );
            const staged: Identity = {
              ...current,
              inboxId: candidate.inboxId,
              expectedInboxId: current.expectedInboxId ?? candidate.inboxId,
              installationId: candidate.candidateInstallationId,
              staleInstallationId:
                candidate.previousInstallationId ?? previousInstallationId,
              xmtpDbPathMode: candidate.databasePathMode,
              installationRepairPending: true,
              needsHistorySync: true,
            };
            await storage.putIdentity(staged);
            setIdentity(staged);
          },
          onInstallationReady: async (ready) => {
            const storage = await getStorage();
            const current = await storage.getIdentityByAddress(identity.address);
            if (!current) {
              throw new Error(
                'The selected identity was removed while browser repair was running. Registration was stopped.'
              );
            }
            if (
              !current.installationRepairPending ||
              !inboxIdsMatch(current.inboxId, ready.inboxId) ||
              !installationIdsMatch(current.installationId, ready.installationId)
            ) {
              throw new Error(
                'The saved browser-repair candidate changed before registration. Registration was stopped.'
              );
            }
            const updated = recordInstallationReady(current, ready);
            await storage.putIdentity(updated);
            setIdentity(updated);
            await ensureInboxStorageNamespace(updated.inboxId, updated);
          },
        }
      );

      const storage = await getStorage();
      const current = await storage.getIdentityByAddress(identity.address);
      if (!current) {
        throw new Error('The repaired identity could not be reloaded from local storage.');
      }
      let completed = completeProvisioning(
        {
          ...current,
          installationRepairPending: false,
          needsHistorySync:
            current.needsHistorySync ||
            (result.historySyncRequired && !result.historySyncRequested),
        },
        result
      );
      if (result.previousInstallationRevoked || result.previousInstallationAbsent) {
        completed = { ...completed, staleInstallationId: undefined };
      }
      await storage.putIdentity(completed);
      setIdentity(completed);
      await ensureInboxStorageNamespace(completed.inboxId, completed);
      return result;
    },
    [setIdentity]
  );

  const addDeviceToExistingWalletInbox = useCallback(
    async (
      targetWalletAddress: string,
      chainId: number | undefined,
      signMessage: (message: string) => Promise<string>,
      options?: {
        walletType?: 'EOA' | 'SCW';
        label?: string;
        onStatus?: (message: string) => void;
      }
    ): Promise<{ inboxId: string; installationId: string; deviceKeyAddress: string }> => {
      const previousSession = useAuthStore.getState();
      const previousNamespace = getStorageNamespace();
      const xmtp = getXmtpClient();
      const walletType = options?.walletType ?? 'EOA';
      const probe = await xmtp.probeIdentity({
        address: targetWalletAddress,
        chainId,
        walletType,
        signMessage,
      });

      if (!probe.inboxId) {
        throw new Error('No existing XMTP inbox was found for that wallet.');
      }
      const targetInboxId = normalizeInboxId(probe.inboxId);
      if (!targetInboxId) {
        throw new Error('XMTP returned an invalid inbox ID for that wallet.');
      }
      if (await isInboxLoadedLocally(targetInboxId)) {
        throw new Error(INBOX_ALREADY_LOADED_MESSAGE);
      }

      if (probe.installationCount >= 10) {
        throw new Error(
          'Installation limit reached (10/10). Revoke an old installation in your wallet settings before connecting this browser.'
        );
      }

      let lastProvisioningPhase = 'preflight';
      const provision = async (provisioningChainId = chainId) => {
        try {
          return await xmtp.provisionExternalWalletDevice({
            walletIdentity: {
              address: targetWalletAddress,
              chainId: provisioningChainId,
              walletType,
              signMessage,
            },
            expectedInboxId: targetInboxId,
            onPhase: async (phase) => {
              lastProvisioningPhase = phase;
              const messages = {
                preflight: 'Checking the target inbox…',
                'opening-manager': 'Opening this browser installation…',
                'manager-ready': 'Browser installation ready…',
                'registering-installation': 'Approve this browser installation in your wallet…',
                'installation-registered': 'Installation approved. Finalizing…',
                'verifying-installation':
                  'Waiting for XMTP to publish this browser installation…',
                'repairing-installation':
                  'Replacing an interrupted browser installation…',
                'associating-key': 'Verifying wallet identity…',
                'association-submitted': 'Verifying…',
                'verifying-association': 'Verifying inbox membership…',
                complete: 'Installation verified. Opening your inbox…',
              } as const;
              options?.onStatus?.(messages[phase] ?? phase);
            },
          });
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          console.error('[Auth] Wallet connection stopped', {
            phase: lastProvisioningPhase,
            message,
          });
          const provisioningError = new Error(
            `Wallet connection stopped during ${lastProvisioningPhase}: ${message}`
          );
          Object.assign(provisioningError, { cause: error });
          throw provisioningError;
        }
      };

      try {
        let provisioned: Awaited<ReturnType<typeof provision>>;
        try {
          provisioned = await provision();
        } catch (error) {
          const mismatch = extractWrongChainIdDetails(
            error instanceof Error ? error.message : String(error)
          );
          const retryChainId = mismatch
            ? getScwRetryChainId(walletType, chainId, mismatch.initiallyAddedWith)
            : null;
          if (mismatch && isLegacyScwChainZeroMismatch(mismatch)) {
            throw new Error(legacyScwChainZeroRecoveryMessage());
          }
          if (retryChainId !== null) {
            provisioned = await provision(retryChainId);
          } else {
            throw error;
          }
        }

        const deviceIdentity: Identity = {
          address: targetWalletAddress,
          publicKey: '',
          privateKey: undefined,
          mnemonic: undefined,
          identityKind: 'wallet',
          walletType,
          walletChainId: chainId,
          inboxId: targetInboxId,
          installationId: provisioned.installationId,
          xmtpDbPathMode: 'inbox-default',
          displayName: options?.label || `${targetWalletAddress.slice(0, 6)}…${targetWalletAddress.slice(-4)}`,
          createdAt: Date.now(),
          needsHistorySync: true,
          expectedInboxId: targetInboxId,
        };

        await setStorageNamespace(targetInboxId);
        const currentStorage = await getStorage();
        await currentStorage.putIdentity(deviceIdentity);
        setIdentity(deviceIdentity);

        const connection = await connectXmtpSafely(
          deviceIdentity.address,
          undefined,
          chainId,
          signMessage,
          {
            registrationPolicy: 'resume-only',
            enableHistorySync: true,
            labelOverride: deviceIdentity.displayName,
            required: true,
            expectedInboxId: targetInboxId,
            expectedInstallationId: provisioned.installationId,
            requestHistorySync: true,
          }
        );

        if (
          !connection ||
          !inboxIdsMatch(connection.inboxId, targetInboxId) ||
          !installationIdsMatch(connection.installationId, provisioned.installationId)
        ) {
          throw new Error(
            'The browser client did not reopen the wallet-approved XMTP installation.'
          );
        }

        setAuthenticated(true);
        setVaultUnlocked(true);
        clearIntentionalEmptyInboxState();

        const registry = useInboxRegistryStore.getState();
        registry.upsertEntry({
          inboxId: targetInboxId,
          displayLabel: deviceIdentity.displayName || targetWalletAddress,
          avatar: deviceIdentity.avatar,
          primaryDisplayIdentity: targetWalletAddress,
          lastOpenedAt: Date.now(),
          hasLocalDB: true,
        });
        registry.setCurrentInbox(targetInboxId);

        return {
          inboxId: targetInboxId,
          installationId: connection.installationId,
          deviceKeyAddress: deviceIdentity.address,
        };
      } catch (error) {
        if (previousSession.isAuthenticated && previousSession.identity) {
          try {
            await setStorageNamespace(previousNamespace);
            setIdentity(previousSession.identity);
            setAuthenticated(true);
            setVaultUnlocked(previousSession.isVaultUnlocked);
            if (previousSession.identity.privateKey) {
              await connectXmtpSafely(
                previousSession.identity.address,
                previousSession.identity.privateKey,
                undefined,
                undefined,
                {
                  registrationPolicy: 'resume-only',
                  enableHistorySync: false,
                  labelOverride: previousSession.identity.displayName,
                  skipRegistryUpdate: true,
                  expectedInboxId:
                    previousSession.identity.expectedInboxId ?? previousSession.identity.inboxId,
                  expectedInstallationId:
                    expectedInstallationForStoredIdentity(previousSession.identity),
                }
              );
            }
          } catch (restoreError) {
            console.warn('[Auth] Failed to restore the prior inbox after wallet connection:', restoreError);
          }
        }
        throw error;
      }
    },
    [connectXmtpSafely, setAuthenticated, setIdentity, setVaultUnlocked]
  );

  const migrateDeviceJoinIdentity = useCallback(
    async (options?: {
      onStatus?: (message: string) => void;
      onPhase?: (phase: string) => void;
    }) => {
      if (!walletAddress) {
        throw new Error('Please connect your wallet to migrate this identity.');
      }
      if (!walletSignMessage) {
        throw new Error('Wallet signing is not available. Please reconnect your wallet.');
      }
      const activeIdentity = authStore.identity;
      if (!activeIdentity) {
        throw new Error('No identity is currently loaded for migration.');
      }
      const signMessage = async (message: string) => {
        return await walletSignMessage(message, walletAddress);
      };

      const migrated = await migrateLegacyDeviceJoinIdentity({
        localIdentity: activeIdentity,
        walletAddress,
        walletChainId,
        walletType: activeIdentity.walletType ?? 'EOA',
        signMessage,
        onPhase: (phase) => {
          options?.onPhase?.(phase);
          const messages: Record<string, string> = {
            preflight: 'Checking wallet and target inbox…',
            'updating-recovery': 'Moving recovery authority to your wallet…',
            'removing-local-account': 'Approve removing the generated local key in your wallet…',
            'verifying-network-state': 'Verifying updated inbox state on the XMTP network…',
            'updating-local-storage': 'Updating local identity storage…',
            complete: 'Migration verified. Opening inbox…',
          };
          options?.onStatus?.(messages[phase] ?? phase);
        },
      });

      setIdentity(migrated);
      setAuthenticated(true);
      setVaultUnlocked(true);
      clearIntentionalEmptyInboxState();

      await connectXmtpSafely(
        migrated.address,
        undefined,
        migrated.walletChainId,
        signMessage,
        {
          registrationPolicy: 'resume-only',
          enableHistorySync: true,
          labelOverride: migrated.displayName,
          required: true,
          expectedInboxId: migrated.inboxId,
          expectedInstallationId: migrated.installationId,
          requestHistorySync: true,
        }
      );

      return migrated;
    },
    [
      walletAddress,
      walletSignMessage,
      walletChainId,
      authStore.identity,
      setIdentity,
      setAuthenticated,
      setVaultUnlocked,
      connectXmtpSafely,
    ]
  );

  return {
    ...authStore,
    createIdentity,
    logout,
    burnIdentity,
    checkExistingIdentity,
    probeIdentity,
    reconnectCurrentIdentity,
    repairCurrentInstallation,
    addDeviceToExistingWalletInbox,
    migrateDeviceJoinIdentity,
  };
}
