const colors = [
  'Red',
  'Blue',
  'Green',
  'Yellow',
  'Purple',
  'Orange',
  'Pink',
  'Brown',
  'Black',
  'White',
] as const;

const animals = [
  'Orca',
  'Dolphin',
  'Whale',
  'Penguin',
  'Seal',
  'Otter',
  'Shark',
  'Turtle',
  'Eagle',
  'Falcon',
  'Hawk',
  'Owl',
  'Fox',
  'Wolf',
  'Bear',
  'Tiger',
  'Lion',
  'Zebra',
  'Giraffe',
  'Elephant',
  'Monkey',
  'Panda',
  'Koala',
  'Kangaroo',
  'Rabbit',
  'Deer',
  'Horse',
  'Bison',
  'Buffalo',
  'Camel',
  'Hippo',
  'Rhino',
  'Leopard',
  'Cheetah',
  'Jaguar',
  'Goat',
  'Sheep',
  'Cow',
  'Pig',
  'Dog',
  'Cat',
  'Goose',
  'Duck',
  'Swan',
  'Frog',
  'Toad',
  'Lizard',
  'Snake',
  'Chimpanzee',
  'Gorilla',
] as const;

export interface SuggestedDisplayName {
  displayName: string;
  color: (typeof colors)[number];
  animal: (typeof animals)[number];
}

export function isAutoGeneratedDisplayName(value?: string | null): boolean {
  const v = value?.trim();
  if (!v) return true;
  const normalized = v.toLowerCase();

  return (
    normalized.startsWith('identity ') ||
    normalized.startsWith('wallet ') ||
    normalized.startsWith('app key ') ||
    normalized.startsWith('0x')
  );
}

export function isUsableNetworkDisplayName(
  value: string | null | undefined,
  identity?: { address?: string; inboxId?: string }
): boolean {
  const trimmed = value?.trim();
  if (!trimmed || isAutoGeneratedDisplayName(trimmed)) {
    return false;
  }
  const normalized = trimmed.toLowerCase();
  if (/^(?:0x)?[0-9a-f]{40}$/.test(normalized) || /^[0-9a-f]{64}$/.test(normalized)) {
    return false;
  }
  return ![identity?.address, identity?.inboxId]
    .map((candidate) => candidate?.trim().toLowerCase())
    .filter(Boolean)
    .includes(normalized);
}

export function suggestAnimalDisplayName(seed?: string | null): SuggestedDisplayName {
  const normalizedSeed = (seed || 'converge').toLowerCase();
  let hash = 2166136261 >>> 0;

  for (let i = 0; i < normalizedSeed.length; i++) {
    hash ^= normalizedSeed.charCodeAt(i);
    hash += (hash << 1) + (hash << 4) + (hash << 7) + (hash << 8) + (hash << 24);
  }

  const color = colors[Math.abs(hash) % colors.length]!;
  const animal = animals[Math.abs(hash >>> 1) % animals.length]!;

  return {
    displayName: `${color} ${animal}`,
    color,
    animal,
  };
}
