import { describe, expect, it } from 'vitest';
import { isAutoGeneratedDisplayName, suggestAnimalDisplayName } from './profile-suggestions';

describe('profile suggestions', () => {
  it('creates deterministic Color Animal display names from a seed', () => {
    const first = suggestAnimalDisplayName('0xabc123');
    const second = suggestAnimalDisplayName('0xAbC123');

    expect(second).toEqual(first);
    expect(first.displayName).toBe(`${first.color} ${first.animal}`);
    expect(first.displayName).toMatch(/^[A-Z][a-z]+ [A-Z][a-z]+$/);
  });

  it('treats generated labels as missing user display names', () => {
    expect(isAutoGeneratedDisplayName(undefined)).toBe(true);
    expect(isAutoGeneratedDisplayName('Identity 0x1234')).toBe(true);
    expect(isAutoGeneratedDisplayName('Wallet 0x1234')).toBe(true);
    expect(isAutoGeneratedDisplayName('App key 0x1234...abcd')).toBe(true);
    expect(isAutoGeneratedDisplayName('0x1234')).toBe(true);
    expect(isAutoGeneratedDisplayName('Purple Otter')).toBe(false);
    expect(isAutoGeneratedDisplayName('Dean Pierce')).toBe(false);
  });
});
