import { describe, expect, it } from 'vitest';
import {
  isAutoGeneratedDisplayName,
  isUsableNetworkDisplayName,
  suggestAnimalDisplayName,
} from './profile-suggestions';

describe('profile suggestions', () => {
  it('creates deterministic Color Animal display names from a seed', () => {
    const first = suggestAnimalDisplayName('0xabc123');
    const second = suggestAnimalDisplayName('0xAbC123');

    expect(second).toEqual(first);
    expect(first.displayName).toBe(`${first.color} ${first.animal}`);
    expect(first.displayName).toMatch(/^[A-Z][a-z]+ [A-Z][a-z]+$/);
  });

  it('treats generated labels as missing user display names', () => {
    expect(isAutoGeneratedDisplayName(undefined)).toBe(true);
    expect(isAutoGeneratedDisplayName('Identity 0x1234')).toBe(true);
    expect(isAutoGeneratedDisplayName('Wallet 0x1234')).toBe(true);
    expect(isAutoGeneratedDisplayName('App key 0x1234...abcd')).toBe(true);
    expect(isAutoGeneratedDisplayName('0x1234')).toBe(true);
    expect(isAutoGeneratedDisplayName('Purple Otter')).toBe(false);
    expect(isAutoGeneratedDisplayName('Dean Pierce')).toBe(false);
  });

  it('rejects address and inbox placeholders returned as network display names', () => {
    const address = `0x${'11'.repeat(20)}`;
    const inboxId = 'a'.repeat(64);
    expect(isUsableNetworkDisplayName(address, { address, inboxId })).toBe(false);
    expect(isUsableNetworkDisplayName(inboxId, { address, inboxId })).toBe(false);
    expect(isUsableNetworkDisplayName('Identity 0x1234', { address, inboxId })).toBe(false);
    expect(isUsableNetworkDisplayName('Alice', { address, inboxId })).toBe(true);
  });
});
